// ============================================================
// CLEAN LIVING — STATIC DATA
// All pure data arrays / lookup objects. No functions.
// Loaded before app.js so all vars are available globally.
// ============================================================

// --- QUOTES ---
var QUOTES = [
  {text: "Just for today, I will try to live through this day only.", source: "Just for Today"},
  {text: "We admitted we were powerless over our addiction.", source: "Step One"},
  {text: "The foundation of recovery is honesty.", source: "Basic Text"},
  {text: "Recovery is a process, not an event.", source: "Fellowship"},
  {text: "Keep coming back - it works if you work it.", source: "Fellowship"},
  {text: "One day at a time.", source: "Fellowship"},
  {text: "We do not have to be alone anymore.", source: "Basic Text"},
  {text: "Pain is inevitable; suffering is optional.", source: "Fellowship"},
  {text: "We will love and support you no matter what.", source: "Fellowship"},
  {text: "God, grant me the serenity to accept the things I cannot change.", source: "Serenity Prayer"}
];
-e 
// --- FOLDER UI ---
var FOLDER_COLORS = ['#e8c97a','#5fcf80','#7ab8e8','#e87a9e','#a87ae8','#e8a87a'];
var FOLDER_EMOJIS = ['📓','📋','🙏','✍️','💭','🌿','⭐','💛','🔑','🧘','💪','🌱','📖','💬','🎯','❤️','🌊','🦋'];
-e 
// --- JOURNAL TYPES & PROMPTS ---
var JOURNAL_TYPES = {
  gratitude: { title: 'Gratitude List', emoji: '&#x1F64F;' },
  spotcheck: { title: 'Spot Check Inventory', emoji: '&#x26A1;' },
  step10:    { title: 'Full Step Inventory', emoji: '&#x1F4CB;' },
  guiding:   { title: 'Guiding Principles', emoji: '&#x1F4D6;' },
  daily:     { title: 'Daily Journal', emoji: '&#x270D;' }
};
var GRATITUDE_PROMPTS = [
  "What's something small that made you smile today?",
  "Who has shown up for you recently, however small?",
  "What's one thing about your body you're grateful for?",
  "Name something you often take for granted.",
  "What's a quality in yourself you appreciate?",
  "Describe a moment of peace you felt recently.",
  "What does having another clean day mean to you?",
  "Who in recovery are you grateful for, and why?",
  "What's something in your home or surroundings you appreciate?",
  "Write about a challenge that helped you grow."
];
var SPOTCHECK_PROMPTS = [
  "Have I been resentful, selfish, dishonest or afraid today?",
  "Do I owe an apology to anyone?",
  "Have I kept something to myself that I should share with my sponsor?",
  "Was I kind and loving to those around me?",
  "Am I HALT right now - Hungry, Angry, Lonely, or Tired?",
  "Did I stay in the present, or was I in yesterday or tomorrow?",
  "What do I need to let go of before I sleep?",
  "Did I do anything today I'm proud of?"
];
var STEP10_QUESTIONS = [
  "Have I taken time today to reconnect with my Higher Power?",
  "Did I seek spiritual guidance today, and if so, how?",
  "How have I been of service to others today?",
  "What am I grateful for that my Higher Power has given me today?",
  "Do I trust that my Higher Power can guide me toward a better way of living?",
  "Have any old patterns or behaviours shown up for me today?",
  "Have I been resentful, selfish, dishonest, or afraid at any point today?",
  "Did I set myself up for disappointment or unrealistic expectations?",
  "Was I kind and loving in my interactions with others today?",
  "Have I been living in the past or the future rather than the present?",
  "Did I allow myself to become obsessed or fixated on anything today?",
  "Have I let myself get too hungry, angry, lonely, or tired today?",
  "Am I taking myself or any situation too seriously right now?",
  "Are there any physical, mental, or spiritual struggles I need to address?",
  "Is there anything I've been keeping from my sponsor that I should share?",
  "Did I experience any intense or overwhelming feelings today - what caused them?",
  "What areas of my life are causing me difficulty right now?",
  "Which character defects showed up in my behaviour today, and how?",
  "Did fear play a role in any of my actions or thoughts today?",
  "Is there anything I did today that I regret or wish I had handled differently?",
  "Is there anything I didn't do today that I know I should have?",
  "Am I genuinely open and willing to change?",
  "Was there conflict in any of my relationships today - what happened?",
  "Am I living with integrity in how I treat the people around me?",
  "Did I cause harm - directly or indirectly - to myself or anyone else today?",
  "Do I owe an apology or amends to anyone?",
  "Where did I go wrong today, and what would I do differently next time?",
  "Did I stay clean today?",
  "Was I compassionate and caring toward myself today?",
  "What feelings did I experience today, and how did I let them guide my choices?",
  "What did I do today to be of service to another person?",
  "What am I feeling good or positive about from today?",
  "What gave me a sense of meaning or satisfaction today?",
  "What did I do today that I want to make sure I repeat?",
  "Did I connect with the fellowship today - a meeting, a phone call, a message?",
  "What do I have to be grateful for today?"
];
var DAILY_PROMPTS = [
  "How am I feeling right now - honestly?",
  "What was the most important moment of my day?",
  "Did anything challenge me today? How did I respond?",
  "Was there a moment today I'm proud of?",
  "What emotions came up for me today, and what triggered them?",
  "Did I show up the way I wanted to today?",
  "What do I want to carry into tomorrow?",
  "How did my relationships feel today?",
  "What is something I need to let go of?",
  "What would I do differently if I could?"
];
-e 
// --- ADMIN ---
var ADMIN_EMAILS = ['clarehobson@icloud.com'];
-e 
// --- REGIONS ---
var REGIONS = {
  'uk': ['UK','United Kingdom','Great Britain','Britain','England','Scotland','Wales','Northern Ireland','GB'],
  'europe': ['Austria','Belgium','Croatia','Czech Republic','Czechia','Denmark','Finland','France','Germany','Greece','Hungary','Iceland','Ireland','Republic of Ireland','Italy','Luxembourg','Malta','Netherlands','The Netherlands','Holland','Norway','Poland','Portugal','Romania','Russia','Serbia','Slovakia','Slovenia','Spain','Sweden','Switzerland','Turkey','Türkiye','Ukraine','Bulgaria','Latvia','Lithuania','Estonia','Moldova','Cyprus','Montenegro','North Macedonia','Bosnia','Bosnia and Herzegovina','Albania','Kosovo','Georgia','Armenia','Azerbaijan','Belarus','Andorra','Liechtenstein','Monaco','San Marino'],
  'north-america': ['USA','United States','United States of America','US','Canada','Mexico'],
  'latin-america': ['Argentina','Brazil','Chile','Colombia','Costa Rica','Cuba','Dominican Republic','Ecuador','El Salvador','Guatemala','Honduras','Jamaica','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Trinidad and Tobago','Uruguay','Venezuela','Bolivia','Guyana','Suriname','Haiti','Belize'],
  'asia': ['Bahrain','China','Hong Kong','India','Indonesia','Israel','Japan','Jordan','Kuwait','Lebanon','Malaysia','Myanmar','Nepal','Oman','Pakistan','Philippines','Qatar','Saudi Arabia','Singapore','South Korea','Korea','Sri Lanka','Taiwan','Thailand','UAE','United Arab Emirates','Vietnam','Viet Nam','Bangladesh','Cambodia','Laos','Mongolia','Brunei','Maldives','Afghanistan','Iraq','Iran','Syria','Yemen'],
  'pacific': ['Australia','Bali','Fiji','New Zealand','Papua New Guinea','Samoa','Tonga','Hawaii'],
  'africa': ['Egypt','Ghana','Kenya','Morocco','Nigeria','South Africa','Tanzania','Uganda','Zimbabwe','Ethiopia','Mozambique','Namibia','Botswana','Rwanda','Zambia','Senegal','Cameroon','Tunisia','Algeria','Libya','Democratic Republic of Congo','Angola','Madagascar','Mauritius'],
  'worldwide': ['Worldwide','worldwide','Online','online','Virtual','International']
};
-e 
// --- MILESTONES ---
var MILESTONES = [
  { days:0,   label:'Just For Today', keytag:'🏳️', message:"You're here. That's not nothing — that's everything. Starting over takes more courage than most people will ever know. The disease doesn't win today. Welcome back." },
  { days:7,   label:'7 Days',         keytag:'🟡', message:"Seven days. One week of choosing differently, every single day. That's not luck — that's you. Keep going." },
  { days:30,  label:'30 Days',        keytag:'🟠', message:"Thirty days clean. A month of showing up when it would have been easier not to. You're building something real here." },
  { days:60,  label:'60 Days',        keytag:'🔴', message:"Sixty days. You've pushed through the part where it gets hard and stayed anyway. That matters more than you know." },
  { days:90,  label:'90 Days',        keytag:'⚪', message:"Ninety days. Three months of a different life. The foundation is yours — you built it, one day at a time." },
  { days:180, label:'6 Months',       keytag:'🟣', message:"Six months clean. Half a year. Whatever you've been doing — keep doing it. It's working." },
  { days:270, label:'9 Months',       keytag:'🟤', message:"Nine months. Long enough to have faced some hard days and come out the other side. You know something now that you didn't know before." },
  { days:365, label:'1 Year',         keytag:'🔵', message:"One year. Three hundred and sixty-five days of choosing life. That keytag is yours — every single day of it earned. Absolutely well done." },
  { days:548, label:'18 Months',      keytag:'🟢', message:"Eighteen months. You've grown into this. Recovery isn't just something you're doing anymore — it's becoming who you are." }
];
-e 
// --- NA STORES ---
var NA_STORES = {
  uk: { label: '🇬🇧 UK Service Office', url: 'https://ukso.biz/order-form/' },
  us: { label: '🇺🇸 NA World Store', url: 'https://cart-us.na.org/catalog' },
  canada: { label: '🇨🇦 NA Canada', url: 'https://cart-ca.na.org' },
  europe: { label: '🇪🇺 NA Europe', url: 'https://cart-eu.na.org' }
};
-e 
// --- MOODS ---
var MOODS = [
{emoji: '😭', label: 'Really struggling'},
{emoji: '😔', label: 'Not great'},
{emoji: '😐', label: 'OK'},
{emoji: '🙂', label: 'Pretty good'},
{emoji: '😁', label: 'Really good'},
{emoji: '🌟', label: 'Amazing'}
];
-e 
// --- FORMAT LABELS ---
var FORMAT_LABELS = ['days', 'years-days', 'full', 'seconds'];
-e 
// --- 365 DAILY REFLECTIONS ---
var DAILY_REFLECTIONS = [
null, // index 0 unused - days are 1-indexed per month
// JANUARY
{m:1,d:1,text:"Yesterday is done. Today is all you have. Use it."},
{m:1,d:2,text:"The fight you keep losing? Stop fighting it. Surrender is where the real work begins."},
{m:1,d:3,text:"Lying to yourself is the most expensive habit you have. And you can't afford it anymore."},
{m:1,d:4,text:"You don't need to see the whole staircase. Just take the next step."},
{m:1,d:5,text:"You don't have to want to. You just have to be willing to try. That's the whole deal."},
{m:1,d:6,text:"Your best thinking got you here. Maybe it's time to try someone else's."},
{m:1,d:7,text:"Find one thing today that you're glad exists. Start there."},
{m:1,d:8,text:"The past is a place you've already been. Stop going back."},
{m:1,d:9,text:"Fighting reality is exhausting. And reality always wins."},
{m:1,d:10,text:"You don't have all the answers. Neither does anyone else. But together we have enough."},
{m:1,d:11,text:"Get out of your own head by getting into someone else's corner."},
{m:1,d:12,text:"Courage today looks like making the call you've been putting off. Make it."},
{m:1,d:13,text:"You don't need certainty. You need enough faith to take the next action."},
{m:1,d:14,text:"Whatever you're white-knuckling right now - ask yourself if holding on is actually helping."},
{m:1,d:15,text:"You know the truth. The question is whether you're ready to stop pretending you don't."},
{m:1,d:16,text:"You are not meant to do this alone. That's not weakness - that's just how this works."},
{m:1,d:17,text:"There is no finish line. There is just today, done well."},
{m:1,d:18,text:"Something shifted when you got clean. Don't overthink it. Just don't waste it."},
{m:1,d:19,text:"The results you want are coming. They're just arriving on recovery's timeline, not yours."},
{m:1,d:20,text:"Resentment is you drinking poison and waiting for them to get sick. Let it go."},
{m:1,d:21,text:"The steps ask hard things of you. So did using. At least this one leads somewhere worth going."},
{m:1,d:22,text:"You are no longer a prisoner of the next fix. That is not nothing. That is everything."},
{m:1,d:23,text:"You spent years becoming someone you didn't like. Recovery gives you the chance to meet who you actually are."},
{m:1,d:24,text:"Your story - the real one, the messy one - is exactly what someone else needs to hear today."},
{m:1,d:25,text:"Peace isn't the absence of problems. It's deciding the problems don't get to run the show."},
{m:1,d:26,text:"Everything you want is on the other side of the thing you keep avoiding."},
{m:1,d:27,text:"Saying I'm struggling is not weakness. Pretending you're fine when you're not - that's what keeps you stuck."},
{m:1,d:28,text:"Your recovery makes mine stronger. That's not a metaphor. That's just true."},
{m:1,d:29,text:"Living clean isn't just about what you stopped doing. It's about what you're building instead."},
{m:1,d:30,text:"Growth feels like discomfort while it's happening. That feeling you're trying to avoid? That's the work."},
{m:1,d:31,text:"How was today, honestly? Not performing for anyone - just you, being real with yourself."},
// FEBRUARY
{m:2,d:1,text:"You are allowed to take up space. You always were."},
{m:2,d:2,text:"The people who matter will respect your boundaries. The ones who don't - that's information."},
{m:2,d:3,text:"An amend isn't an apology. It's a change in behaviour. Words are easy. Show up differently."},
{m:2,d:4,text:"You cannot pour from an empty cup. Looking after yourself is not selfish. It's essential."},
{m:2,d:5,text:"Trust is rebuilt in small moments, not grand gestures. Keep showing up."},
{m:2,d:6,text:"You don't have to earn your place in recovery. You belong here. Full stop."},
{m:2,d:7,text:"Relationships in recovery require honesty. Not brutal honesty. Just honesty."},
{m:2,d:8,text:"The version of you that used - they were doing the best they could. So is this version."},
{m:2,d:9,text:"Setting a boundary isn't pushing someone away. It's deciding what you will and won't accept."},
{m:2,d:10,text:"You spent years numbing feelings. Now the feelings are back. That's not a problem. That's progress."},
{m:2,d:11,text:"Self-worth isn't built in a day. It's built in every moment you choose yourself over the chaos."},
{m:2,d:12,text:"Not every relationship survives recovery. Some aren't meant to. Let them go with grace."},
{m:2,d:13,text:"You don't need to be liked by everyone. You need to be honest with yourself. Start there."},
{m:2,d:14,text:"Love in recovery starts with the person in the mirror. Everything else flows from that."},
{m:2,d:15,text:"You are not your past. But you are responsible for what you do with it."},
{m:2,d:16,text:"Needing people isn't a weakness. Isolation is what nearly killed you. Connection is what's saving you."},
{m:2,d:17,text:"You taught people how to treat you. Recovery gives you the chance to reset those lessons."},
{m:2,d:18,text:"Grief is part of recovery. You're allowed to mourn the years, the relationships, the time. Feel it."},
{m:2,d:19,text:"Making amends to yourself is also part of the work. Don't skip that one."},
{m:2,d:20,text:"Comparison is a trap. Your recovery is yours. Someone else's journey is none of your business."},
{m:2,d:21,text:"Boundaries said with kindness are still boundaries. You don't have to be cruel to be clear."},
{m:2,d:22,text:"The people who were there when it was hard - hold them close. They're rare."},
{m:2,d:23,text:"You are worth the effort of getting better. In case nobody told you that today."},
{m:2,d:24,text:"Healthy relationships feel boring to someone used to chaos. Boring is good. Boring is safe."},
{m:2,d:25,text:"You can love someone and still not allow their behaviour in your life. Both things are true."},
{m:2,d:26,text:"The work you're doing on yourself - it ripples out. People around you feel it, even if they don't say so."},
{m:2,d:27,text:"Forgive yourself first. Everything else gets easier after that."},
{m:2,d:28,text:"You made it through February. Some days that's the whole victory."},
{m:2,d:29,text:"Leap years remind us that time doesn't always follow the rules. Neither does recovery. Keep going anyway."},
// MARCH
{m:3,d:1,text:"Thinking about changing and actually changing are two very different things. Which one are you doing?"},
{m:3,d:2,text:"You can't think your way into right action. You have to act your way into right thinking."},
{m:3,d:3,text:"Responsibility isn't about blame. It's about ownership. Own your part. Then move forward."},
{m:3,d:4,text:"The meeting you don't want to go to is usually the one you need most."},
{m:3,d:5,text:"Excuses keep you exactly where you are. What's one thing you can do today instead of explaining why you can't?"},
{m:3,d:6,text:"Procrastination in recovery isn't laziness. It's usually fear. Name the fear. Then do the thing anyway."},
{m:3,d:7,text:"You've already done the hardest thing - you got clean. The rest is just showing up."},
{m:3,d:8,text:"Making things right doesn't erase the past. But it changes your relationship with it."},
{m:3,d:9,text:"Action is the answer to almost every problem in recovery. What's your next one?"},
{m:3,d:10,text:"You don't have to feel motivated to move. Movement creates motivation. Start moving."},
{m:3,d:11,text:"The step you're avoiding - that's the one with all the freedom behind it."},
{m:3,d:12,text:"Clean time doesn't mean comfortable time. Stay uncomfortable. That's where the growth is."},
{m:3,d:13,text:"Every time you do the right thing when nobody's watching, you're becoming someone you can trust."},
{m:3,d:14,text:"You have everything you need to get through today. Just today. That's enough."},
{m:3,d:15,text:"Half measures got you half a life. Full commitment is what recovery actually asks of you."},
{m:3,d:16,text:"The programme works if you work it. Not if you observe it. Not if you think about it. Work it."},
{m:3,d:17,text:"Showing up imperfectly is infinitely better than not showing up at all."},
{m:3,d:18,text:"You don't have to have it all figured out. You just have to keep going."},
{m:3,d:19,text:"The person you're becoming requires you to leave behind some of who you were. That's okay."},
{m:3,d:20,text:"Spring reminds us - things that looked dead can come back to life. You're proof of that."},
{m:3,d:21,text:"Take the action. Let go of the outcome. That's the whole formula."},
{m:3,d:22,text:"If you're waiting until you feel ready, you'll be waiting forever. Ready is a myth."},
{m:3,d:23,text:"Your word is your integrity. In recovery, keep them aligned."},
{m:3,d:24,text:"One honest conversation today could change everything. Who do you need to call?"},
{m:3,d:25,text:"Discipline is just commitment on the days you don't feel like it."},
{m:3,d:26,text:"The amends you keep putting off - they're heavier than the conversation will be."},
{m:3,d:27,text:"You are capable of far more than your addiction ever let you believe."},
{m:3,d:28,text:"Don't wait for the perfect moment. The perfect moment is the one you're in."},
{m:3,d:29,text:"Every clean day is an act of defiance against everything that tried to destroy you."},
{m:3,d:30,text:"Progress isn't always visible. Sometimes it's just not going backwards. That counts."},
{m:3,d:31,text:"Quarter of the year done. You're still here, still clean, still trying. That's not small."},
// APRIL
{m:4,d:1,text:"Recovery isn't a joke. But you're allowed to laugh at yourself. Humour is part of healing."},
{m:4,d:2,text:"A fearless moral inventory means fearless. Not comfortable. Not selective. Fearless."},
{m:4,d:3,text:"Your character defects aren't unique. They're human. What matters is what you do with them."},
{m:4,d:4,text:"Asking for help is the most efficient thing you can do. It still takes guts. Ask anyway."},
{m:4,d:5,text:"The things you're most ashamed of - those are exactly what the programme is designed for."},
{m:4,d:6,text:"New growth looks messy before it looks beautiful. You're in the messy bit. Keep going."},
{m:4,d:7,text:"Honesty in step work isn't about punishing yourself. It's about finally seeing yourself clearly."},
{m:4,d:8,text:"You cannot fix what you refuse to look at."},
{m:4,d:9,text:"Defects of character aren't life sentences. They're patterns you can change. One day at a time."},
{m:4,d:10,text:"Sharing your inventory doesn't make you weak. It makes the weight something you no longer carry alone."},
{m:4,d:11,text:"The truth will set you free. But first it will make you deeply uncomfortable. Sit with that."},
{m:4,d:12,text:"Recovery asks you to look at yourself honestly. Most people never do that. You're doing the hard thing."},
{m:4,d:13,text:"Self-pity is seductive. It feels like feeling, but it keeps you stuck. Notice it. Move through it."},
{m:4,d:14,text:"You are not defined by what you did. You are defined by what you do now."},
{m:4,d:15,text:"Spring cleaning isn't just for houses. What are you holding onto that needs to go?"},
{m:4,d:16,text:"The sponsor who pushes you is the one who believes you can handle more. Let them be right."},
{m:4,d:17,text:"Your secrets keep you sick. Your honesty sets you free."},
{m:4,d:18,text:"Perfectionism is just fear with better PR. Done is better than perfect. Every time."},
{m:4,d:19,text:"You've survived 100% of your worst days so far. Remember that today."},
{m:4,d:20,text:"Growth isn't comfortable. Neither was using. Choose the discomfort that leads somewhere."},
{m:4,d:21,text:"When the programme feels hard, remember - you've done harder things in worse conditions."},
{m:4,d:22,text:"Tend to your recovery the way you'd tend to something precious. Because it is."},
{m:4,d:23,text:"Resentments are rent-free tenants living in your head. Evict them."},
{m:4,d:24,text:"The character you're building in recovery - that's the real you. Keep building."},
{m:4,d:25,text:"You don't have to be the same person you were last year. That's the whole point."},
{m:4,d:26,text:"Share honestly. Listen openly. Show up fully. That's the whole of fellowship."},
{m:4,d:27,text:"Courage isn't the absence of fear. It's doing it scared."},
{m:4,d:28,text:"You are not too broken to get better. Nobody is."},
{m:4,d:29,text:"The step you've been avoiding is the door you need to walk through."},
{m:4,d:30,text:"Four months in - or wherever you are. The effort you're making matters more than you know."},
// MAY
{m:5,d:1,text:"You can't think straight when you're running on empty. Sleep. Eat. Rest. Then tackle it."},
{m:5,d:2,text:"Meditation isn't emptying your mind. It's noticing what's in it without letting it run the show."},
{m:5,d:3,text:"Be as kind to yourself today as you would be to a newcomer. You deserve that too."},
{m:5,d:4,text:"Conscious contact with a higher power doesn't have to look like anyone else's. Make it yours."},
{m:5,d:5,text:"Mental health is part of recovery. Not a separate issue. Not a weakness. Part of it."},
{m:5,d:6,text:"Slowing down is not giving up. Sometimes it's the most productive thing you can do."},
{m:5,d:7,text:"Prayer doesn't have to be formal. Sometimes it's just - help. That's enough."},
{m:5,d:8,text:"You are allowed to have a bad day without it meaning everything is falling apart."},
{m:5,d:9,text:"Self-compassion is not letting yourself off the hook. It's treating yourself with the same grace you'd offer anyone else."},
{m:5,d:10,text:"Anxiety in recovery is real. Talk about it. Get support. Don't white-knuckle it alone."},
{m:5,d:11,text:"Five minutes of stillness a day can change everything. Try it before you dismiss it."},
{m:5,d:12,text:"Your higher power doesn't require you to have it all figured out. Just a willingness to listen."},
{m:5,d:13,text:"The voice that tells you you're not good enough - that's not the truth. It's just old noise."},
{m:5,d:14,text:"Rest is not a reward for finishing. It's part of the work."},
{m:5,d:15,text:"You've been hard on yourself for years. What would it feel like to ease up, just for today?"},
{m:5,d:16,text:"Spirituality in recovery isn't about religion. It's about connection - to yourself, to others, to something bigger."},
{m:5,d:17,text:"Feelings are information, not instructions. Notice them. You don't have to act on every one."},
{m:5,d:18,text:"The mind that once obsessed over using can learn to obsess over healing. Point it in the right direction."},
{m:5,d:19,text:"You are allowed to ask for what you need. People cannot read your mind."},
{m:5,d:20,text:"When everything feels too much - break it down. Just this hour. Just this task. Just this breath."},
{m:5,d:21,text:"Gratitude and anxiety cannot fully occupy the same space. Lean into gratitude."},
{m:5,d:22,text:"Your emotional sobriety matters as much as your physical sobriety. Work on both."},
{m:5,d:23,text:"You don't have to earn rest. You are allowed to simply be, without achieving."},
{m:5,d:24,text:"The programme gives you tools. But you have to pick them up."},
{m:5,d:25,text:"Some days recovery feels like flying. Some days it feels like crawling. Both count."},
{m:5,d:26,text:"What would you tell a friend who was thinking what you're thinking right now? Tell yourself that."},
{m:5,d:27,text:"Silence is not emptiness. It's where you learn to hear yourself again."},
{m:5,d:28,text:"You've come too far to be undone by a feeling. Feel it. Let it pass."},
{m:5,d:29,text:"Connection is the opposite of addiction. Reach out today - to anyone."},
{m:5,d:30,text:"You are not your thoughts. You are the one noticing them."},
{m:5,d:31,text:"Five months. Or five days. Or five years. However long - it matters. You matter."},
// JUNE
{m:6,d:1,text:"The newcomer in the room is you, six months or six years ago. Remember that."},
{m:6,d:2,text:"Service work isn't optional extra credit. It's part of what keeps you well."},
{m:6,d:3,text:"Your sponsor sees you more clearly than you see yourself right now. Trust that."},
{m:6,d:4,text:"The best thing you can do for your recovery today is help someone else with theirs."},
{m:6,d:5,text:"Fellowship is imperfect because people are imperfect. Stay anyway."},
{m:6,d:6,text:"You have something no professional can offer - lived experience. That's powerful. Use it."},
{m:6,d:7,text:"Showing up for someone else when you're struggling is one of the fastest ways to feel better."},
{m:6,d:8,text:"The programme keeps working because people keep giving it away. Be one of those people."},
{m:6,d:9,text:"Your story isn't just yours. It belongs to everyone who needs to hear it."},
{m:6,d:10,text:"Sponsorship is a two-way street. The sponsor learns as much as the sponsee."},
{m:6,d:11,text:"You don't have to be perfect to help someone. You just have to be honest."},
{m:6,d:12,text:"Community isn't just the meeting room. It's the coffee after. The phone call. The showing up."},
{m:6,d:13,text:"Someone today is where you were on your worst day. Your presence could change everything for them."},
{m:6,d:14,text:"You can't keep what you don't give away. Give generously."},
{m:6,d:15,text:"The longest journey in recovery is from the head to the heart. Fellowship helps get you there."},
{m:6,d:16,text:"Real connection requires vulnerability. Take the risk. It's worth it."},
{m:6,d:17,text:"If nobody's called you in a while - you make the call. That's how it works."},
{m:6,d:18,text:"Your clean time is evidence that recovery is possible. Someone needs to see that today."},
{m:6,d:19,text:"We recover in community, not in isolation. Reach out before you need to, not after."},
{m:6,d:20,text:"Don't wait to be asked to help. Look for the need and meet it."},
{m:6,d:21,text:"The meeting where you feel most like leaving is usually the one you most need to stay for."},
{m:6,d:22,text:"What you put into your recovery is exactly what you'll get out of it."},
{m:6,d:23,text:"Being of service costs you nothing and gives you everything. Strange maths. True maths."},
{m:6,d:24,text:"Your recovery has value beyond yourself. Never forget that."},
{m:6,d:25,text:"Every person in that room chose to be there. That's not nothing. That's everything."},
{m:6,d:26,text:"The person who hasn't picked up their chips yet - they might need to see yours. Show up."},
{m:6,d:27,text:"You belong in the rooms. Not despite your past. Because of it."},
{m:6,d:28,text:"Carry the message, not the mess. Get your own house in order, then help someone else."},
{m:6,d:29,text:"Recovery is not a solo sport. Stop treating it like one."},
{m:6,d:30,text:"Half a year. Look at what community has helped you build."},
// JULY
{m:7,d:1,text:"You are free. Actually free. Not the illusion of freedom that using sold you - real freedom."},
{m:7,d:2,text:"Life on life's terms doesn't mean life is hard. It also means sunsets, laughter, and clean mornings."},
{m:7,d:3,text:"You have earned the right to enjoy today. Don't waste it waiting for something to go wrong."},
{m:7,d:4,text:"Independence means something different now. You are no longer dependent on a substance to face your day."},
{m:7,d:5,text:"Fun without consequences. That's real. You can have that now. Let yourself."},
{m:7,d:6,text:"Recovery gave you your life back. Are you actually living it?"},
{m:7,d:7,text:"The senses you numbed are back. The warmth of the sun, the taste of good food, the sound of laughter. Notice them."},
{m:7,d:8,text:"You are allowed to be happy. Fully, unguiltily happy. Let that in."},
{m:7,d:9,text:"Some of the best moments of your life are still ahead of you. Stay clean long enough to live them."},
{m:7,d:10,text:"Today is a good day to do something you love. Not tomorrow. Today."},
{m:7,d:11,text:"The life you dreamed of in early recovery - are you building it? If not, start today."},
{m:7,d:12,text:"Boredom is not dangerous. Boredom is just a sign that you need to find something that interests you."},
{m:7,d:13,text:"Recovery doesn't mean a small, careful life. It means a full one. Claim it."},
{m:7,d:14,text:"You deserve good things. This is not up for debate."},
{m:7,d:15,text:"Go outside. Call someone you love. Eat something good. Do one thing today just because it feels good."},
{m:7,d:16,text:"The addict in you will try to convince you that happiness is suspicious. It isn't. Enjoy it."},
{m:7,d:17,text:"You've done the hard work. Now let yourself reap some of it."},
{m:7,d:18,text:"Laughter is medicine. Find something funny today. Laugh at yourself if necessary."},
{m:7,d:19,text:"Who do you want to be? Not who you were. Who do you want to be? Start being that person today."},
{m:7,d:20,text:"The summer of your recovery. Make it count."},
{m:7,d:21,text:"Adventure is available to the clean. Go find some."},
{m:7,d:22,text:"Rest without guilt. Play without anxiety. Exist without having to earn it. This is recovery."},
{m:7,d:23,text:"Presence is the greatest gift you can give. Be here, fully, today."},
{m:7,d:24,text:"You are allowed to want more from life. Recovery is a beginning, not a ceiling."},
{m:7,d:25,text:"Find your joy. Not what's supposed to bring joy - what actually brings you joy. Pursue that."},
{m:7,d:26,text:"The people who love you are glad you're here. Really, truly glad. Let that land."},
{m:7,d:27,text:"Recovery made space for everything - love, connection, beauty, meaning. Fill that space."},
{m:7,d:28,text:"Don't sleepwalk through the good days. They are the point."},
{m:7,d:29,text:"You've been given a second chance at life. Take it seriously by actually living."},
{m:7,d:30,text:"Summer won't last forever. Neither will today. Be in it."},
{m:7,d:31,text:"Seven months. Seven seasons of change. You're still here. Still growing."},
// AUGUST
{m:8,d:1,text:"Complacency is the quiet enemy of long-term recovery. Stay sharp."},
{m:8,d:2,text:"Success in recovery can be as dangerous as struggle. Stay humble either way."},
{m:8,d:3,text:"The longer you're clean, the easier it is to forget why you stopped. Don't forget."},
{m:8,d:4,text:"Keep doing the basics - meetings, steps, service, honesty. They work because they're simple."},
{m:8,d:5,text:"Staying grounded when things are going well is its own kind of discipline."},
{m:8,d:6,text:"You've come far enough to know that this is worth protecting. Protect it."},
{m:8,d:7,text:"Old behaviour in new clothes is still old behaviour. Stay honest about what's really going on."},
{m:8,d:8,text:"Long-term recovery isn't about never struggling. It's about having the tools to handle the struggle."},
{m:8,d:9,text:"Your recovery is an asset. Treat it like one."},
{m:8,d:10,text:"The danger zones in long-term recovery are the H.A.L.T ones - hungry, angry, lonely, tired. Check in."},
{m:8,d:11,text:"You cannot afford to get too comfortable. Recovery requires continued attention."},
{m:8,d:12,text:"Gratitude is not a feeling you wait for. It's a practice you maintain."},
{m:8,d:13,text:"The programme that got you here will keep you here - if you keep using it."},
{m:8,d:14,text:"One day at a time still applies at ten years as much as ten days."},
{m:8,d:15,text:"Never let your clean time make you think you're immune. Nobody is."},
{m:8,d:16,text:"Growth never stops in recovery. If you feel like you've arrived, look again."},
{m:8,d:17,text:"The foundations you've built - keep strengthening them. They're carrying a life."},
{m:8,d:18,text:"Somewhere, someone is on day one because of a relapse that started with complacency. Stay vigilant."},
{m:8,d:19,text:"Your best days in recovery are available to you. But they require your continued effort."},
{m:8,d:20,text:"Recovery is not a thing you had. It's a thing you're doing. Keep doing it."},
{m:8,d:21,text:"The tools don't stop working. People stop using them. Keep picking them up."},
{m:8,d:22,text:"Long-term recovery is built on thousands of small decisions. Today's decision matters."},
{m:8,d:23,text:"Stay connected to new people in recovery. They'll remind you of what's at stake."},
{m:8,d:24,text:"There's no amount of clean time that makes you bulletproof. Stay close to the programme."},
{m:8,d:25,text:"Continue to do the work. The rewards compound over time in ways that will astonish you."},
{m:8,d:26,text:"What got you clean won't necessarily keep you clean. Keep growing, keep learning."},
{m:8,d:27,text:"You are still a work in progress. That's not an insult - it's the most hopeful thing there is."},
{m:8,d:28,text:"The hardest relapse to see coming is the one after a long stretch of good days. Keep watching."},
{m:8,d:29,text:"Protecting your recovery is protecting your life. Take it seriously."},
{m:8,d:30,text:"Look how far you've come. Now keep going."},
{m:8,d:31,text:"Eight months - or eight years. Today is what matters. Today, choose recovery again."},
// SEPTEMBER
{m:9,d:1,text:"Back to basics isn't a punishment. It's a reminder of what actually works."},
{m:9,d:2,text:"When did you last do a proper inventory? If you can't remember, it's probably time."},
{m:9,d:3,text:"Routine isn't boring in recovery. Routine is scaffolding. It holds you up."},
{m:9,d:4,text:"Slip back into the basics when things get hard - meetings, sponsor, steps. They still work."},
{m:9,d:5,text:"What's working in your recovery right now? Do more of that."},
{m:9,d:6,text:"What isn't working? Be honest. Then do something about it."},
{m:9,d:7,text:"The programme is only as strong as your current relationship with it."},
{m:9,d:8,text:"You don't graduate from the steps. You cycle back through them, and each time you go deeper."},
{m:9,d:9,text:"Something feeling off? That's information. Pay attention to it."},
{m:9,d:10,text:"Mental health check - how are you actually doing? Not the version you tell people. The real version."},
{m:9,d:11,text:"Recovery asked for your whole life. Not just the using part. The whole thing. Give it."},
{m:9,d:12,text:"Is your recovery expanding or contracting? Both are possible. Choose expansion."},
{m:9,d:13,text:"New season, same commitment. The leaves change. Your programme doesn't have to."},
{m:9,d:14,text:"The sponsor relationship only works if you're honest. Are you being honest?"},
{m:9,d:15,text:"Maintenance work in recovery isn't glamorous. It's essential."},
{m:9,d:16,text:"What habits have crept back in that you need to look at? You know what they are."},
{m:9,d:17,text:"Being around longer doesn't mean needing the basics less. It might mean needing them more."},
{m:9,d:18,text:"Step Ten exists because life keeps happening and we keep having to check ourselves."},
{m:9,d:19,text:"A daily inventory is just asking - how am I doing, really? Ask it."},
{m:9,d:20,text:"Autumn is a natural time to let things go. What are you holding onto that needs to go?"},
{m:9,d:21,text:"Recovery is seasonal. Some periods feel rich and full. Some feel bare. Both are part of it."},
{m:9,d:22,text:"Don't wait until you're in crisis to pick the tools back up. Pick them up now."},
{m:9,d:23,text:"The basics aren't below you. They're beneath everything you've built. Don't neglect them."},
{m:9,d:24,text:"A quiet day in recovery is not a wasted day. Peace is part of the programme."},
{m:9,d:25,text:"Check your connections - to your higher power, to your sponsor, to your fellow recovering people. Are they strong?"},
{m:9,d:26,text:"If everything feels fine, stay curious about why. Fine can sometimes be numbness in disguise."},
{m:9,d:27,text:"Your programme should be evolving with you. Is it?"},
{m:9,d:28,text:"The willingness to keep looking at yourself honestly - that's what long-term recovery is built on."},
{m:9,d:29,text:"Three quarters of the year. What have you learned about yourself? What will you do with it?"},
{m:9,d:30,text:"September done. You're still here. Still choosing. That's everything."},
// OCTOBER
{m:10,d:1,text:"Fear is a liar. It tells you that you can't handle what's coming. You've handled worse. Keep going."},
{m:10,d:2,text:"Grief and recovery are not strangers. You are allowed to mourn. Feel it. Don't use over it."},
{m:10,d:3,text:"The dark seasons come for everyone. Recovery gives you a way through that doesn't make things worse."},
{m:10,d:4,text:"Resilience isn't about never falling. It's about getting up one more time than you fall."},
{m:10,d:5,text:"Loss is part of life. Using was never actually a solution to it. You know that now."},
{m:10,d:6,text:"Face the thing you're most afraid of. It rarely turns out to be as catastrophic as your mind said."},
{m:10,d:7,text:"When everything feels dark, do the next right thing. Just one. Then the next."},
{m:10,d:8,text:"Hard times in recovery are not a sign that recovery isn't working. They're a sign that life is happening."},
{m:10,d:9,text:"You have survived dark periods before - and you came through them. You will come through this one too."},
{m:10,d:10,text:"Your feelings will not kill you. They will pass. All of them."},
{m:10,d:11,text:"The courage to keep going when you can't see the point - that's real courage. Keep going."},
{m:10,d:12,text:"Difficult emotions are not emergencies. They are information. Breathe. Get support. Don't use."},
{m:10,d:13,text:"You are stronger than the hardest day you've ever faced. And you're still here."},
{m:10,d:14,text:"When you can't find the light, be the light. For yourself, for someone else."},
{m:10,d:15,text:"Recovery doesn't promise an easy life. It promises a real one. Hold onto that."},
{m:10,d:16,text:"Ask for help before you're desperate. Desperation makes good decision-making harder."},
{m:10,d:17,text:"The night is darkest before dawn. That's not a cliche. It's something people in recovery know to be true."},
{m:10,d:18,text:"You are not alone in this. Someone in your fellowship is available right now. Call them."},
{m:10,d:19,text:"Struggle does not mean failure. It means you're in the middle of something. Stay in the middle."},
{m:10,d:20,text:"There is a version of you on the other side of this that you cannot yet see. Keep moving toward it."},
{m:10,d:21,text:"Bad days are not evidence that recovery isn't worth it. They're just bad days."},
{m:10,d:22,text:"Let people in when it's hard. That's what they're there for."},
{m:10,d:23,text:"You don't have to be strong all the time. You just have to keep going."},
{m:10,d:24,text:"The tools in your kit were built for exactly this. Reach for them."},
{m:10,d:25,text:"One of the bravest things in recovery is admitting - I am not okay right now. Say it."},
{m:10,d:26,text:"This too shall pass. It always does."},
{m:10,d:27,text:"Dark seasons grow the deepest roots. You are growing."},
{m:10,d:28,text:"When you get through this - and you will - you'll have something new to offer someone else."},
{m:10,d:29,text:"Your recovery has survived hard times before. It will survive this one."},
{m:10,d:30,text:"Hold on. Just hold on."},
{m:10,d:31,text:"Whatever is haunting you right now - you don't have to face it alone. Reach out."},
// NOVEMBER
{m:11,d:1,text:"Gratitude is not toxic positivity. It's choosing to notice what's real and good, even when hard things are also real."},
{m:11,d:2,text:"Count what you have, not what you've lost. Both lists are long. Focus on the right one."},
{m:11,d:3,text:"You woke up clean today. For some people, that is the miracle. Let it be yours too."},
{m:11,d:4,text:"Giving thanks for your recovery doesn't mean pretending the journey wasn't brutal. It was. And here you are."},
{m:11,d:5,text:"Name three things today that exist because you got clean. Hold them."},
{m:11,d:6,text:"Gratitude shared is gratitude doubled. Tell someone today what they mean to you."},
{m:11,d:7,text:"The life you have today - the ordinary, unremarkable Tuesday of it - was once something you could only dream of."},
{m:11,d:8,text:"Someone is grateful you're in their life. Do you know who? Have you told them you're grateful for them?"},
{m:11,d:9,text:"Recovery has given you the ability to feel again. Gratitude is one of those feelings. Let it in."},
{m:11,d:10,text:"Even on bad days there is something. Find it. It matters."},
{m:11,d:11,text:"Remembering where you came from isn't living in the past. It's fuelling the gratitude for where you are."},
{m:11,d:12,text:"The relationships that survived your addiction - those people loved you when you couldn't love yourself. Honour that."},
{m:11,d:13,text:"Generosity flows naturally from gratitude. What can you give today?"},
{m:11,d:14,text:"Your clean time is a gift - to yourself and to everyone who loves you."},
{m:11,d:15,text:"Gratitude is a daily practice, not a feeling you wait to arrive. Practice it."},
{m:11,d:16,text:"The ordinary things - a warm drink, a safe place to sleep, a day without chaos - are extraordinary. See them."},
{m:11,d:17,text:"Someone prayed for your recovery before you were willing to. Be grateful for that person."},
{m:11,d:18,text:"Tell the people who helped you that they helped you. Don't assume they know."},
{m:11,d:19,text:"Gratitude and resentment cannot live in the same moment. Choose which one to feed."},
{m:11,d:20,text:"The worst day clean is still better than the best day using. Remember that when it's hard."},
{m:11,d:21,text:"Your presence in recovery makes the rooms richer. That's worth being grateful for."},
{m:11,d:22,text:"What do you take for granted that you once prayed for? See it today."},
{m:11,d:23,text:"Be grateful for the struggle too. It made you into someone who can help others."},
{m:11,d:24,text:"Gratitude for small things leads to the ability to receive big things. Start small."},
{m:11,d:25,text:"The fellowship that catches you when you fall - that is a gift beyond measure."},
{m:11,d:26,text:"Recovery gave you back the capacity to love and be loved. That is not nothing."},
{m:11,d:27,text:"Thank the people who showed up for you before you could show up for yourself."},
{m:11,d:28,text:"Count your blessings. Not because everything is perfect - but because perspective is a practice."},
{m:11,d:29,text:"You are someone's miracle. Do you know that?"},
{m:11,d:30,text:"End of November. Grateful for the hard months and the good ones. Both taught you something."},
// DECEMBER
{m:12,d:1,text:"The festive season is not always easy in recovery. Plan ahead. Stay close to your support."},
{m:12,d:2,text:"Year end reflection: who were you in January? Who are you now? The distance between those two is your work."},
{m:12,d:3,text:"Family gatherings can be hard. You don't have to white-knuckle it alone. Have an exit plan. Have a person."},
{m:12,d:4,text:"The holidays are not a reason to use. They are a reason to double down on your support."},
{m:12,d:5,text:"You have survived every difficult Christmas so far. You can survive this one too."},
{m:12,d:6,text:"Expectation is the enemy of acceptance. Go into the season expecting it to be imperfect. Be right."},
{m:12,d:7,text:"Plan your recovery support for the festive period like you'd plan anything important. It is important."},
{m:12,d:8,text:"It's okay if the holidays feel complicated. You don't have to pretend it's all magic."},
{m:12,d:9,text:"Stay in contact with your support network during December. Don't go quiet."},
{m:12,d:10,text:"The lights, the noise, the pressure - none of it is worth your recovery. Protect it."},
{m:12,d:11,text:"Give yourself permission to leave situations that threaten your recovery. Every time."},
{m:12,d:12,text:"Someone in your fellowship will be struggling this December. Check in on them."},
{m:12,d:13,text:"Clean celebrations are possible. Plan for them. They can be genuinely joyful."},
{m:12,d:14,text:"Your recovery is the best gift you have given yourself and everyone who loves you."},
{m:12,d:15,text:"If this time of year brings grief - let it. Grief is not relapse. Feel it. Get support."},
{m:12,d:16,text:"Comparison at Christmas is toxic. Your recovery is not less valuable because it looks different to others."},
{m:12,d:17,text:"The new year will come whether you're ready or not. You don't have to have it all figured out."},
{m:12,d:18,text:"End of year inventory: where have you grown? Where do you still need to? Both answers matter."},
{m:12,d:19,text:"Stay close to what keeps you well. Especially now."},
{m:12,d:20,text:"Recovery through the winter takes courage. You have it. Use it."},
{m:12,d:21,text:"The longest night. If you're in darkness right now - you are not alone. Reach out."},
{m:12,d:22,text:"Clean time through the hard seasons means more. You're earning something real."},
{m:12,d:23,text:"Don't isolate. Whatever it takes - a meeting, a call, a coffee. Stay connected."},
{m:12,d:24,text:"Christmas Eve in recovery. You don't have to feel what you think you should feel. Just stay clean."},
{m:12,d:25,text:"Today, however it looks, you are clean. That is the gift. It is enough."},
{m:12,d:26,text:"The day after. Still here. Still clean. That matters."},
{m:12,d:27,text:"The quiet days between Christmas and New Year - use them for reflection, not rumination."},
{m:12,d:28,text:"Look back at who you were this time last year. See the growth, even when it's hard to."},
{m:12,d:29,text:"Three days left of the year. What do you want to take into the next one?"},
{m:12,d:30,text:"Tomorrow is New Year's Eve. Plan for it. Recovery doesn't take a night off."},
{m:12,d:31,text:"Another year clean. Or your first clean New Year's Eve. Either way - this is extraordinary. You did it."}
];
-e 
// --- MEETING FINDER DATA ---
var meetingFinderData = [

  {c:['uk'],f:'🇬🇧',n:'UK Meeting Finder',d:'Search by postcode, town or county',u:'https://meetings.ukna.org/meeting/search'},
  {c:['uk'],f:'🇬🇧',n:'UK Online Meetings',d:'450+ online UK NA meetings',u:'https://meetings.ukna.org/meeting/search/online'},
  {c:['ireland'],f:'🇮🇪',n:'Ireland Meeting Finder',d:'Find meetings across Ireland',u:'https://www.na-ireland.org/na-meetings/'},
  {c:['ireland'],f:'🇮🇪',n:'Ireland Online Meetings',d:'Online NA meetings in Ireland',u:'https://www.na-ireland.org/online-meetings/'},

  {c:['belgium'],f:'🇧🇪',n:'Belgium',d:'Find NA meetings in Belgium',u:'https://na-belgium.org/en/meetings/'},
  {c:['bulgaria'],f:'🇧🇬',n:'Bulgaria',d:'NA Bulgaria',u:'https://www.na-bulgaria.com/index.en.html'},
  {c:['croatia'],f:'🇭🇷',n:'Croatia',d:'NA Croatia',u:'https://nacroatia.org'},
  {c:['czech'],f:'🇨🇿',n:'Czech / Slovak Region',d:'NA Czech/Slovak meetings',u:'https://www.anonymninarkomani.cz'},
  {c:['denmark'],f:'🇩🇰',n:'Denmark',d:'Find meetings across Denmark',u:'https://www.nadanmark.dk/moeder/'},
  {c:['finland'],f:'🇫🇮',n:'Finland',d:'NA meetings in Finland',u:'https://www.nasuomi.org/kokoukset/'},
  {c:['france'],f:'🇫🇷',n:'France',d:'In-person meetings in France',u:'https://www.narcotiquesanonymes.org/reunions-physiques/'},
  {c:['germany'],f:'🇩🇪',n:'Germany / Austria',d:'All meetings in Germany & Austria',u:'https://narcotics-anonymous.de/en/all-meetings/'},
  {c:['greece'],f:'🇬🇷',n:'Greece',d:'NA meetings in Greece',u:'https://www.na-greece.gr/en/\u03c3\u03c5\u03b3\u03ba\u03b5\u03bd\u03c4\u03c1\u03c9\u03c3\u03b5\u03b9\u03c3/diadiktyakes/'},
  {c:['hungary'],f:'🇭🇺',n:'Hungary',d:'NA Hungary meeting list',u:'https://nahungary.hu/en/gyuleslista/'},
  {c:['iceland'],f:'🇮🇸',n:'Iceland',d:'NA meetings in Iceland',u:'https://nai.is/en/meetings/'},
  {c:['italy'],f:'🇮🇹',n:'Italy',d:'NA meetings across Italy',u:'https://na-italia.org/riunioni/'},
  {c:['latvia'],f:'🇱🇻',n:'Latvia',d:'Meeting locations in Latvia',u:'https://www.na-latvija.lv/sapulcu_vietas'},
  {c:['lithuania'],f:'🇱🇹',n:'Lithuania',d:'NA Lithuania contacts & meetings',u:'https://lietuvos-na.lt/narkomanai-anonimai-kontaktai/'},
  {c:['malta'],f:'🇲🇹',n:'Malta / Gozo',d:'NA meetings in Malta',u:'https://na-malta.org/meetings/'},
  {c:['moldova'],f:'🇲🇩',n:'Moldova',d:'NA Moldova',u:'https://namoldova.org'},
  {c:['netherlands'],f:'🇳🇱',n:'Netherlands',d:'NA meetings in the Netherlands',u:'https://www.nanederland.nl/meetings/'},
  {c:['norway'],f:'🇳🇴',n:'Norway',d:'NA meetings in Norway',u:'https://nanorge.org/moter/'},
  {c:['poland'],f:'🇵🇱',n:'Poland',d:'NA meeting list for Poland',u:'https://anonimowinarkomani.org/lista-mityngow/'},
  {c:['portugal'],f:'🇵🇹',n:'Portugal',d:'In-person meetings in Portugal',u:'https://na-pt.org/index.php/pt/reunioes-header/presenciais'},
  {c:['romania'],f:'🇷🇴',n:'Romania',d:'NA meetings in Romania',u:'https://narcoticii-anonimi.ro/intalniri'},
  {c:['russian'],f:'🇷🇺',n:'Russian-Speaking Groups',d:'Russian-speaking meetings outside Russia',u:'https://na-tranzit.org/gruppy/russkoyazychnye-gruppy-v-drugih-stranah'},
  {c:['serbia'],f:'🇷🇸',n:'Serbia',d:'NA meetings in Serbia',u:'https://www.na-srbija.org/sastanci.php'},
  {c:['slovenia'],f:'🇸🇮',n:'Slovenia',d:'NA Slovenia',u:'https://www.na-slovenija.org'},
  {c:['spain'],f:'🇪🇸',n:'Spain',d:'NA groups across Spain',u:'https://www.narcoticosanonimos.es/grupos/'},
  {c:['sweden'],f:'🇸🇪',n:'Sweden',d:'NA Sweden meeting list',u:'https://www.nasverige.org/moteslista/'},
  {c:['switzerland'],f:'🇨🇭',n:'Switzerland',d:'NA meetings in Switzerland',u:'https://narcotics-anonymous.ch/en/meetings/'},
  {c:['turkey'],f:'🇹🇷',n:'Turkey',d:'NA meetings in Turkey',u:'https://na-turkiye.org/na-toplantilari/'},
  {c:['ukraine'],f:'🇺🇦',n:'Ukraine',d:'NA groups across Ukraine',u:'https://na-ua.org/sobraniya-an-v-ukraine/gruppy-an-v-ukraine'},
  {c:['usa'],f:'🇺🇸',n:'USA Meeting Finder',d:'Find NA meetings across the United States',u:'https://usa-na.org/find-na/'},
  {c:['hawaii'],f:'🌺',n:'East Hawaii Region',d:'East Hawaii meeting schedule',u:'https://na-hawaii.org/meeting-schedules/east-hawaii-schedule/'},
  {c:['hawaii'],f:'🌺',n:'West Hawaii Region',d:'West Hawaii meeting schedule',u:'https://na-hawaii.org/meeting-schedules/west-hawaii-schedule/'},
  {c:['hawaii'],f:'🌺',n:'Maui Region',d:'Maui meeting schedule',u:'https://na-hawaii.org/meeting-schedules/maui-schedule/'},
  {c:['hawaii'],f:'🌺',n:'Molokai Region',d:'Molokai meeting schedule',u:'https://na-hawaii.org/meeting-schedules/molokai-schedule/'},
  {c:['hawaii'],f:'🌺',n:'Lanai Region',d:'Lanai meeting schedule',u:'https://na-hawaii.org/meeting-schedules/lanai-schedule/'},
  {c:['hawaii'],f:'🌺',n:'Oahu Region',d:'Oahu meeting schedule',u:'https://na-hawaii.org/meeting-schedules/oahu-schedule/'},
  {c:['hawaii'],f:'🌺',n:'Kauai Region',d:'Kauai meeting schedule',u:'https://na-hawaii.org/meeting-schedules/kauai-schedule/'},
  {c:['hawaii'],f:'🌺',n:'Lōkahi Kauai Region',d:'Lōkahi Kauai area meetings',u:'https://na-hawaii.org/meeting-schedules/lokahi-kauai-area/'},
  {c:['canada'],f:'🇨🇦',n:'British Columbia',d:'BC Region NA meeting search',u:'https://bcrna.ca/meeting/'},
  {c:['canada'],f:'🇨🇦',n:'Edmonton & Area',d:'Edmonton Area NA meetings',u:'https://eana.ca/meetings/'},
  {c:['canada'],f:'🇨🇦',n:'Calgary & Southern Alberta',d:'Chinook Area NA meetings',u:'https://chinookna.org/meetings/'},
  {c:['canada'],f:'🇨🇦',n:'Central Alberta',d:'Central Alberta Area NA meetings',u:'https://www.centralalbertaareana.com/meetings'},
  {c:['canada'],f:'🇨🇦',n:'Toronto',d:'Toronto Area NA meetings',u:'https://www.torontona.org/meetings'},
  {c:['canada'],f:'🇨🇦',n:'Ottawa',d:'Ottawa Area NA meetings',u:'https://ottawana.org/meet.html'},
  {c:['canada'],f:'🇨🇦',n:'Ontario Region',d:'All Ontario areas — Hamilton, Niagara, London, Sudbury & more',u:'https://www.orscna.org/meetings'},
  {c:['canada'],f:'🇨🇦',n:'Quebec (French)',d:'Narcotiques Anonymes Quebec',u:'https://www.naquebec.org'},
  {c:['canada'],f:'🇨🇦',n:'Montreal (English)',d:'English Area NA Montreal',u:'https://www.eanamontreal.org'},
  {c:['canada'],f:'🇨🇦',n:'Newfoundland & Labrador',d:'NL Area NA — St. Johns, Burin, Carbonear, Labrador City',u:'https://www.nlareana.ca/in-person-meetings.html'},
  {c:['canada'],f:'🇨🇦',n:'Atlantic Canada',d:'New Brunswick, Nova Scotia & PEI meetings',u:'https://canaacna.org'},
  {c:['mexico'],f:'🇲🇽',n:'Mexico — National',d:'NA Mexico national directory',u:'https://www.narcoticosanonimos.org.mx/Grupos.html'},
  {c:['mexico'],f:'🇲🇽',n:'Mexico — Centro Costas',d:'Centro Costas region',u:'https://regioncentrocostas.org/?page_id=135'},
  {c:['mexico'],f:'🇲🇽',n:'Mexico — West Region',d:'Occidente region',u:'https://naregionoccidente.org/directorio-grupos/'},
  {c:['mexico'],f:'🇲🇽',n:'Mexico — Baja Region',d:'Northwestern Mexico',u:'https://www.bajasonna.com/contact-3'},
  {c:['costarica'],f:'🇨🇷',n:'Costa Rica — NA Meetings',d:'NA meetings across Costa Rica',u:'https://narcoticosanonimoscr.org/nuestros-grupos/'},
  {c:['costarica'],f:'🇨🇷',n:'Costa Rica — English Speaking',d:'English-speaking meetings for visitors',u:'https://www.costaricatreatmentcenter.com/na-meetings-in-costa-rica/'},
  {c:['brazil'],f:'🇧🇷',n:'Brazil — Find a Meeting',d:'Search NA meetings by state across Brazil',u:'https://www.na.org.br/grupos'},
  {c:['brazil'],f:'📄',n:'Brazil — Download Meeting List PDF',d:'Download the full Brazil NA meeting list by region',u:'https://www.na.org.br/gerar-pdf-lista-de-grupos/'},
  {c:['bahamas'],f:'🇧🇸',n:'Bahamas — NA Meetings',d:'NA meetings across the Bahamas',u:'https://bahamasna.org/meetings-2/'},
  {c:['bali'],f:'🇮🇩',n:'Bali',d:'NA meetings in Bali',u:'https://na-bali.org/na-meetings-bali/'},
  {c:['hongkong'],f:'🇭🇰',n:'Hong Kong',d:'NA meetings in Hong Kong',u:'https://www.nahongkong.org/na-meetings'},
  {c:['india'],f:'🇮🇳',n:'India',d:'NA meetings across India',u:'https://naindia.in/na-meetings-in-india/'},
  {c:['iran'],f:'🇮🇷',n:'Iran',d:'Face-to-face meetings in Iran',u:'https://meeting.nairan1.org/en/group/face-to-face'},
  {c:['israel'],f:'🇮🇱',n:'Israel',d:'NA meetings in Israel',u:'https://naisrael.org.il/en/meetings-3-2/'},
  {c:['japan'],f:'🇯🇵',n:'Hokkaido Region',d:'Sapporo, Obihiro, Kushiro, Chitose, Otaru, Kitami',u:'https://najapan.org/meeting/hokkaido/'},
  {c:['japan'],f:'🇯🇵',n:'Tohoku Region',d:'Sendai, Aomori, Iwate, Akita, Yamagata, Fukushima, Niigata',u:'https://najapan.org/meeting/tohoku/'},
  {c:['japan'],f:'🇯🇵',n:'Kita-Kanto Region',d:'Fukushima, Ibaraki, Tochigi, Niigata',u:'https://najapan.org/meeting/kitakanto/'},
  {c:['japan'],f:'🇯🇵',n:'Gunma Region',d:'Gunma prefecture',u:'https://najapan.org/meeting/gunma/'},
  {c:['japan'],f:'🇯🇵',n:'Kanto Region',d:'Tokyo, Saitama, Chiba',u:'https://najapan.org/meeting/kanto/'},
  {c:['japan'],f:'🇯🇵',n:'Minami-Kanto Region',d:'Yokohama, Kanagawa, Shizuoka, Yamanashi, Nagano',u:'https://najapan.org/meeting/minamikanto/'},
  {c:['japan'],f:'🇯🇵',n:'Chubu Region',d:'Gifu, Aichi, Mie',u:'https://najapan.org/meeting/chubu/'},
  {c:['japan'],f:'🇯🇵',n:'Kansai Region',d:'Osaka, Kyoto, Kobe, Nara, Wakayama, Shiga',u:'https://najapan.org/meeting/kansai/'},
  {c:['japan'],f:'🇯🇵',n:'Chugoku Region',d:'Hiroshima, Okayama, Tottori, Shimane, Yamaguchi',u:'https://najapan.org/meeting/cyugoku/'},
  {c:['japan'],f:'🇯🇵',n:'Shikoku Region',d:'Tokushima, Kagawa, Ehime, Kochi',u:'https://najapan.org/meeting/shikoku/'},
  {c:['japan'],f:'🇯🇵',n:'Kyushu Region',d:'Fukuoka, Saga, Nagasaki, Kumamoto, Oita, Miyazaki, Kagoshima',u:'https://najapan.org/meeting/kyusyu/'},
  {c:['japan'],f:'🇯🇵',n:'Okinawa Region',d:'Okinawa prefecture',u:'https://najapan.org/meeting/okinawa/'},
  {c:['japan'],f:'🇯🇵',n:'Japan — English Information',d:'English-language info for visitors',u:'https://najapan.org/english-information/'},
  {c:['japan'],f:'🇯🇵',n:'Japan — Full List (Japanese PDF)',d:'Complete nationwide list',u:'https://najapan.org/pdf/NALIST_J.pdf'},
  {c:['nepal'],f:'🇳🇵',n:'Nepal',d:'NA meetings in Nepal',u:'https://nanepal.org/na-meetings/'},
  {c:['saudiarabia'],f:'🇸🇦',n:'Saudi Arabia',d:'NA meetings in Saudi Arabia',u:'https://saudina.org/meetings'},
  {c:['singapore'],f:'🇸🇬',n:'Singapore',d:'NA meetings in Singapore',u:'https://nasingapore.org'},
  {c:['seasia','thailand'],f:'🌏',n:'SE Asia Meetings',d:'Meetings across South East Asia',u:'https://na-thailand.org/meetings-near-thailand/'},
  {c:['thailand'],f:'🇹🇭',n:'Thailand',d:'NA meetings in Thailand',u:'https://na-thailand.org/na-meetings-in-thailand/'},
  {c:['vietnam'],f:'🇻🇳',n:'Vietnam',d:'NA in Vietnam via APFNA',u:'https://www.apfna.org/vietnam'},
  {c:['australia'],f:'🇦🇺',n:'Australia Meeting Search',d:'Search all Australian NA meetings',u:'https://www.na.org.au/multi/meetings/'},
  {c:['australia'],f:'🇦🇺',n:'NSW Meetings',d:'New South Wales',u:'https://www.na.org.au/multi/nsw-meetings/'},
  {c:['australia'],f:'🇦🇺',n:'Victoria',d:'Victoria area',u:'https://www.na.org.au/multi/victoria-area/'},
  {c:['australia'],f:'🇦🇺',n:'Queensland',d:'Queensland',u:'https://www.na.org.au/multi/queensland-meetings/'},
  {c:['australia'],f:'🇦🇺',n:'Western Australia',d:'WA area',u:'https://www.na.org.au/multi/western-australia-area/'},
  {c:['australia'],f:'🇦🇺',n:'South Australia',d:'SA area',u:'https://www.na.org.au/multi/south-australia-area/'},
  {c:['australia'],f:'🇦🇺',n:'Canberra / ACT',d:'ACT area',u:'https://www.na.org.au/multi/canberra-and-surrounds-meetings/'},
  {c:['australia'],f:'🇦🇺',n:'Tasmania',d:'Tasmania area',u:'https://www.na.org.au/multi/tasmania-area/'},
  {c:['australia'],f:'🇦🇺',n:'Northern Territory',d:'NT area',u:'https://www.na.org.au/multi/northern-territory-area/'},
  {c:['newzealand'],f:'🇳🇿',n:'New Zealand — Current Meetings',d:'Current meeting list',u:'https://nzna.org/?current-meeting-list=4/'},
  {c:['newzealand'],f:'🇳🇿',n:'New Zealand — All Meetings',d:'Full meeting directory',u:'https://nzna.org/meetings/'},
  {c:['egypt'],f:'🇪🇬',n:'Egypt',d:'NA meetings in Egypt',u:'https://naegypt.org/ar/meetings'},
  {c:['southafrica'],f:'🇿🇦',n:'Johannesburg',d:'NA meetings in Johannesburg',u:'https://na.org.za/jhb/'},
  {c:['southafrica'],f:'🇿🇦',n:'KwaZulu-Natal',d:'NA meetings in KwaZulu-Natal',u:'https://na.org.za/kzn/na-meetings/'},
  {c:['southafrica'],f:'🇿🇦',n:'Pretoria',d:'NA meetings in Pretoria',u:'https://na.org.za/pta/na-meetings/'},
  {c:['southafrica'],f:'🇿🇦',n:'Western Cape',d:'NA meetings in the Western Cape',u:'https://na.org.za/wc/in-person-meetings/'},
  {c:['southafrica'],f:'📄',n:'Western Cape Meeting List PDF',d:'Download the Western Cape meeting list',u:'https://na.org.za/wp-content/uploads/na-western-cape-meeting-list.pdf'}
];
-e 
// --- COUNTRY MEETING DATA ---
var maltaMeetings = [
  {day:'Monday',time:'7:30 PM',name:'Millennium Chapel',venue:'Millennium Chapel',addr:'Church St, St Julian\'s STJ 3043',type:'Closed',region:'Malta (English)'},
  {day:'Monday',time:'5:30 PM',name:'Oasi Foundation',venue:'Oasi Foundation Trunciera',addr:'5 Triq Wied Sara, Victoria VCT 2963',type:'Closed',region:'Gozo (Maltese)'},
  {day:'Tuesday',time:'7:00 PM',name:'Millennium Chapel',venue:'Millennium Chapel',addr:'Church St, St Julian\'s STJ 3043',type:'Closed',region:'Malta (Maltese)'},
  {day:'Tuesday',time:'8:00 PM',name:'Women Only (Online)',venue:'Zoom Meeting',addr:'ID: 208 850 0955 \u00B7 PW: jftmalta',type:'Closed (Women)',region:'Online (English)'},
  {day:'Wednesday',time:'6:00 PM',name:'Caritas Foundation',venue:'Caritas Foundation',addr:'Triq Mountbatten, Hamrun HMR 1577',type:'Closed',region:'Malta (Eng/Maltese)'},
  {day:'Wednesday',time:'7:30 PM',name:'Online Meeting',venue:'Zoom Meeting',addr:'ID: 208 850 0955 \u00B7 PW: jftmalta',type:'Closed',region:'Online (Maltese)'},
  {day:'Thursday',time:'11:00 AM',name:'Online Meeting',venue:'Zoom Meeting',addr:'ID: 208 850 0955 \u00B7 PW: jftmalta',type:'Open',region:'Online (Eng/Maltese)'},
  {day:'Thursday',time:'5:30 PM',name:'Oasi Foundation',venue:'Oasi Foundation Trunciera',addr:'5 Triq Wied Sara, Victoria VCT 2963',type:'Closed',region:'Gozo (Maltese)'},
  {day:'Thursday',time:'7:30 PM',name:'Millennium Chapel',venue:'Millennium Chapel',addr:'Church St, St Julian\'s STJ 3043',type:'Closed',region:'Malta (English)'},
  {day:'Friday',time:'7:00 PM',name:'Online Meeting',venue:'Zoom Meeting',addr:'ID: 208 850 0955 \u00B7 PW: jftmalta',type:'Closed',region:'Online (Maltese)'},
  {day:'Saturday',time:'5:00 PM',name:'Millennium Chapel (Hybrid)',venue:'Millennium Chapel + Zoom',addr:'Church St, St Julian\'s STJ 3043',type:'Closed',region:'Malta (English)'},
  {day:'Saturday',time:'6:00 PM',name:'Oasi Foundation',venue:'Oasi Foundation Trunciera',addr:'5 Triq Wied Sara, Victoria VCT 2963',type:'Closed',region:'Gozo (Maltese)'},
  {day:'Sunday',time:'11:00 AM',name:'Online Meeting',venue:'Zoom Meeting',addr:'ID: 208 850 0955 \u00B7 PW: jftmalta',type:'Open',region:'Online (Eng/Maltese)'},
  {day:'Sunday',time:'7:00 PM',name:'Hamrun Meeting',venue:'16 Kuncizzjoni',addr:'Hamrun',type:'Open',region:'Malta (Maltese)'}
];

// ============================================================
// NEW ZEALAND MEETINGS
// ============================================================
var nzMeetings = [
  // NORTHLAND / WHANGAREI
  {day:'Monday',time:'6:30 PM',name:'Mt. Zion NA',venue:'Mt Zion Church',addr:'36 Heke St, Kaikohe',region:'Northland'},
  {day:'Monday',time:'6:30 PM',name:'Recovery Together',venue:'Archie Bull Hall',addr:'Behind St Paul\'s Church, 11 Kaiwaka Mangawhai Rd',region:'Northland'},
  {day:'Tuesday',time:'6:00 PM',name:'How It Works',venue:'1B Deveron Street',addr:'Regent, Whangarei',region:'Northland'},
  {day:'Wednesday',time:'6:30 PM',name:'FFN Maori Common Needs',venue:'Hope Church',addr:'234 Commerce St, Kaitaia',region:'Northland'},
  {day:'Wednesday',time:'6:30 PM',name:'Kerikeri Wednesday',venue:'St James Anglican Church Hall',addr:'209 Kerikeri Rd',region:'Northland'},
  {day:'Friday',time:'1:00 PM',name:'Tunatahi',venue:'Community Mental Health & Addictions',addr:'77 Awakino Rd, Dargaville',region:'Northland'},
  {day:'Friday',time:'7:30 PM',name:'Freedom Friday',venue:'73 Water Street',addr:'Whangarei',region:'Northland'},
  // AUCKLAND
  {day:'Sunday',time:'11:15 AM',name:'Daylight',venue:'Epsom Community Centre',addr:'202 Gillies Ave, Epsom',region:'Auckland'},
  {day:'Sunday',time:'2:00 PM',name:'Reo Ngakau',venue:'Salvation Army Building',addr:'3 Tobin St, Pukekohe',region:'Auckland'},
  {day:'Sunday',time:'6:00 PM',name:'Black Keys',venue:'Grey Lynn Community Centre',addr:'510 Richmond Rd, Grey Lynn',region:'Auckland'},
  {day:'Sunday',time:'7:00 PM',name:'No Gram Like The Program',venue:'Gracegate Community Centre',addr:'42 Parkway Dr, Rosedale',region:'Auckland'},
  {day:'Sunday',time:'7:00 PM',name:'Serenity Sunday',venue:'Hibiscus Community House',addr:'216 Hibiscus Coast Hwy, Orewa',region:'Auckland'},
  {day:'Sunday',time:'7:00 PM',name:'Spiritual Recovery',venue:'Mt Eden War Memorial Hall',addr:'487 Dominion Rd, Mt Eden',region:'Auckland'},
  {day:'Monday',time:'12:30 PM',name:'Kickstart Mondays',venue:'Baptist Church Hall',addr:'43 Jervois Rd, Ponsonby',region:'Auckland'},
  {day:'Monday',time:'1:00 PM',name:'Westside',venue:'Te Atatu Baptist Church',addr:'448 Old Te Atatu Rd',region:'Auckland'},
  {day:'Monday',time:'7:00 PM',name:'Cabbage Patch',venue:'C.I. Church',addr:'794 East Coast Rd, Albany',region:'Auckland'},
  {day:'Monday',time:'7:00 PM',name:'Highland Park Serenity',venue:'Highland Park Community House',addr:'47 Aviemore Dr, Pakuranga',region:'Auckland'},
  {day:'Monday',time:'7:00 PM',name:'LGBTQI Meeting',venue:'All Saints Church',addr:'284 Ponsonby Rd',region:'Auckland'},
  {day:'Monday',time:'7:00 PM',name:'Southside Serenity',venue:'Papakura East Presbyterian',addr:'87 Settlement Rd, Papakura',region:'Auckland'},
  {day:'Monday',time:'7:00 PM',name:'Topic (Hybrid)',venue:'Ponsonby Baptist Church',addr:'43 Jervois Rd, Ponsonby',type:'Hybrid',region:'Auckland'},
  {day:'Monday',time:'7:30 PM',name:'Albany Gratitude',venue:'Albany Village Hall',addr:'Albany Hwy & Library Lane',region:'Auckland'},
  {day:'Monday',time:'7:30 PM',name:'Men\'s Meeting',venue:'126 Meeting Rooms',addr:'126 Point Chevalier Rd',type:'Men Only',region:'Auckland'},
  {day:'Tuesday',time:'10:30 AM',name:'The Coffee Meeting',venue:'YMCA Taylor Room',addr:'773 New North Rd, Mt Albert',region:'Auckland'},
  {day:'Tuesday',time:'1:00 PM',name:'Ponsonby Couch',venue:'Baptist Church Hall',addr:'43 Jervois Rd, Ponsonby',region:'Auckland'},
  {day:'Tuesday',time:'7:00 PM',name:'Experience Strength Hope',venue:'Freemans Bay Community Centre',addr:'52 Hepburn St',region:'Auckland'},
  {day:'Tuesday',time:'7:00 PM',name:'Tuesday Recovery',venue:'Mahurangi Vineyard Church',addr:'5 Pulham Rd, Warkworth',region:'Auckland'},
  {day:'Tuesday',time:'7:30 PM',name:'Onehunga Steps To Freedom',venue:'Centennial Hall',addr:'79 Grey St, Onehunga',region:'Auckland'},
  {day:'Tuesday',time:'7:30 PM',name:'Unity',venue:'25 Saint Jude Street',addr:'Avondale',region:'Auckland'},
  {day:'Wednesday',time:'12:30 PM',name:'Young NA',venue:'Grey Lynn Community Centre',addr:'510 Richmond Rd',region:'Auckland'},
  {day:'Wednesday',time:'7:00 PM',name:'12 Steps',venue:'All Saints Church Hall',addr:'284 Ponsonby Rd',region:'Auckland'},
  {day:'Wednesday',time:'7:00 PM',name:'NA All Day Traditions',venue:'St Luke\'s Anglican Church',addr:'3 Russell Rd, Manurewa',region:'Auckland'},
  {day:'Wednesday',time:'7:30 PM',name:'No Rules',venue:'Glendowie Community Hall',addr:'83 Crossfield Rd, Glendowie',region:'Auckland'},
  {day:'Thursday',time:'10:30 AM',name:'Great South Gratitude',venue:'CareNZ Building',addr:'503 Great South Rd, Manukau',region:'Auckland'},
  {day:'Thursday',time:'12:30 PM',name:'Happy Hour',venue:'Ponsonby Baptist Church',addr:'43 Jervois Rd',region:'Auckland'},
  {day:'Thursday',time:'7:00 PM',name:'Women\'s Lamplight',venue:'Grey Lynn Community Centre',addr:'510 Richmond Rd',type:'Women Only',region:'Auckland'},
  {day:'Thursday',time:'7:30 PM',name:'Fellowship West',venue:'Odyssey House',addr:'4/3029 Great North Rd, New Lynn',region:'Auckland'},
  {day:'Thursday',time:'7:30 PM',name:'North Shore Gratitude',venue:'Onepoto Awhina',addr:'65 Pearn Cres, Northcote',region:'Auckland'},
  {day:'Friday',time:'12:15 PM',name:'Basic Text Meeting',venue:'Mt Eden Village Centre',addr:'449 Mt Eden Rd',region:'Auckland'},
  {day:'Friday',time:'7:00 PM',name:'Friday Freedom',venue:'St Peter\'s Anglican',addr:'11 Killarney St, Takapuna',region:'Auckland'},
  {day:'Friday',time:'7:00 PM',name:'Maori Common Needs',venue:'Te Ha Oranga',addr:'1 Rendall Pl, Eden Terrace',region:'Auckland'},
  {day:'Friday',time:'7:00 PM',name:'New Beginnings',venue:'Te Atatu Baptist Church',addr:'448 Old Te Atatu Rd',region:'Auckland'},
  {day:'Friday',time:'7:15 PM',name:'Friday Night Topic',venue:'Grey Lynn Community Centre',addr:'510 Richmond Rd',region:'Auckland'},
  {day:'Saturday',time:'10:30 AM',name:'Y Recovery?',venue:'YMCA Taylor Room',addr:'773 New North Rd, Mt Albert',region:'Auckland'},
  {day:'Saturday',time:'11:00 AM',name:'Up & At Em',venue:'St John the Baptist Anglican',addr:'47 Church St, Northcote Point',region:'Auckland'},
  {day:'Saturday',time:'1:15 PM',name:'Newcomers',venue:'Saint Benedicts Church',addr:'1 St Benedicts St, Eden Terrace',region:'Auckland'},
  {day:'Saturday',time:'6:30 PM',name:'Saturday Night Live',venue:'Ponsonby Community Centre',addr:'20 Ponsonby Terrace',region:'Auckland'},
  {day:'Saturday',time:'7:00 PM',name:'Steps and Unity',venue:'Friendship House',addr:'20 Putney Way, Manukau',region:'Auckland'},
  {day:'Saturday',time:'9:00 PM',name:'In All Our Affairs (Candlelight)',venue:'Unitarian Church',addr:'1A Ponsonby Rd, Grey Lynn',region:'Auckland'},
  // HAMILTON / WAIKATO
  {day:'Sunday',time:'5:00 PM',name:'Mana Recovery',venue:'Te Whare Korowai',addr:'480 Anglesea St, Hamilton',type:'Men Only',region:'Hamilton'},
  {day:'Sunday',time:'5:00 PM',name:'Waikato Women\'s NA',venue:'28 Manning St',addr:'Hamilton Central',type:'Women Only',region:'Hamilton'},
  {day:'Monday',time:'7:00 PM',name:'Learning to Live Clean',venue:'Te Whare Korowai',addr:'480 Anglesea St',region:'Hamilton'},
  {day:'Tuesday',time:'7:00 PM',name:'Hope in Connection',venue:'St Peter\'s Cathedral',addr:'51 Victoria St, Hamilton',region:'Hamilton'},
  {day:'Wednesday',time:'12:30 PM',name:'Staying Clean',venue:'Support House Whanau Room',addr:'28 Manning St',region:'Hamilton'},
  {day:'Wednesday',time:'7:30 PM',name:'Wednesday Candlelight',venue:'Te Whanau Putahi',addr:'37 Oxford St, Fairfield',region:'Hamilton'},
  {day:'Thursday',time:'5:30 PM',name:'Drop The Monkey',venue:'St Peter\'s Cathedral',addr:'51 Victoria St',type:'Closed',region:'Hamilton'},
  {day:'Friday',time:'12:30 PM',name:'The How Meeting',venue:'Community Centre',addr:'184 Grandview Rd, Nawton',region:'Hamilton'},
  {day:'Friday',time:'7:00 PM',name:'Cambridge NA',venue:'24 Raleigh Street',addr:'Leamington, Cambridge',region:'Hamilton'},
  {day:'Saturday',time:'5:00 PM',name:'Hope and Freedom',venue:'28 Manning St',addr:'Hamilton',region:'Hamilton'},
  // TAURANGA
  {day:'Sunday',time:'7:00 PM',name:'Compass Finds Direction',venue:'Hanmer Clinic',addr:'1235 Cameron Rd, Greerton',region:'Tauranga'},
  {day:'Monday',time:'7:00 PM',name:'Monday Night Living Clean',venue:'St Marys Anglican',addr:'33/19 Girven Rd, Mt Maunganui',region:'Tauranga'},
  {day:'Tuesday',time:'10:30 AM',name:'Serenity Sisters',venue:'87 Courtney Road',addr:'Parkvale',type:'Women Only',region:'Tauranga'},
  {day:'Thursday',time:'6:00 PM',name:'Tauranga Men\'s',venue:'St Peter\'s',addr:'130 Spring St',type:'Men Only',region:'Tauranga'},
  // ROTORUA
  {day:'Tuesday',time:'7:00 PM',name:'Ngati NA',venue:'St Lukes Anglican',addr:'1223 Amohia St, Rotorua',region:'Rotorua'},
  // GISBORNE
  {day:'Monday',time:'7:00 AM',name:'Put Your Recovery First',venue:'Level 2, 100 Grey St',addr:'Gisborne',region:'Gisborne'},
  {day:'Wednesday',time:'6:30 PM',name:'Gisborne Wednesday',venue:'Level 2, 100 Grey St',addr:'Gisborne',region:'Gisborne'},
  {day:'Saturday',time:'8:00 AM',name:'First To See The Sun',venue:'Tamarau Community Church',addr:'2 Steele Rd',region:'Gisborne'},
  // TAUPO
  {day:'Tuesday',time:'7:00 PM',name:'Taupo NA',venue:'St Andrew\'s Anglican',addr:'91 Titiraupenga St, Taupo',region:'Taupo'},
  // TARANAKI
  {day:'Monday',time:'12:15 PM',name:'Monday Lunchtime',venue:'St Joseph\'s Church',addr:'151 Devon St West, New Plymouth',region:'Taranaki'},
  {day:'Monday',time:'6:30 PM',name:'Helping Willing Addicts',venue:'Assembly of God Church',addr:'192 High St, Hawera',type:'Hybrid',region:'Taranaki'},
  {day:'Tuesday',time:'7:00 PM',name:'Steps and Traditions',venue:'St Josephs Church Hall',addr:'151 Devon St West',region:'Taranaki'},
  {day:'Thursday',time:'6:00 PM',name:'Everyday NA JFT',venue:'St Josephs Church Hall',addr:'151 Devon St West',region:'Taranaki'},
  {day:'Saturday',time:'5:00 PM',name:'Taranaki Topic',venue:'St Josephs Church Hall',addr:'151 Devon St West',region:'Taranaki'},
  // NAPIER / HASTINGS
  {day:'Sunday',time:'6:30 PM',name:'Rainbow Hour LGBT+',venue:'Blank Canvas',addr:'41 Station St, Napier South',region:'Napier / Hastings'},
  {day:'Monday',time:'6:30 PM',name:'Maori Common Needs',venue:'Trinity Methodist Church',addr:'32 Clive Square East, Napier',region:'Napier / Hastings'},
  {day:'Tuesday',time:'7:30 PM',name:'Spiritual Principle A Day',venue:'Trinity Methodist',addr:'32 Clive Square East, Napier',region:'Napier / Hastings'},
  {day:'Wednesday',time:'6:30 PM',name:'Steps and Literature',venue:'Trinity Methodist',addr:'32 Clive Square East, Napier',region:'Napier / Hastings'},
  {day:'Thursday',time:'7:30 PM',name:'We Do Recover',venue:'Frimley Park Hall',addr:'317 Hapuku St, Hastings',region:'Napier / Hastings'},
  {day:'Friday',time:'7:30 PM',name:'Lamplit Topic',venue:'Trinity Methodist',addr:'32 Clive Square East, Napier',region:'Napier / Hastings'},
  {day:'Saturday',time:'4:30 PM',name:'Women\'s Unity - Rise Up',venue:'All Saints Church',addr:'23 Puketapu Rd, Taradale',type:'Women Only',region:'Napier / Hastings'},
  {day:'Saturday',time:'7:30 PM',name:'Staying Alive Q&A',venue:'All Saints Church',addr:'23 Puketapu Rd, Taradale',region:'Napier / Hastings'},
  // WHANGANUI
  {day:'Sunday',time:'7:00 PM',name:'Start the Week',venue:'St Pauls',addr:'120 Guyton St, Whanganui',region:'Whanganui'},
  {day:'Tuesday',time:'7:00 PM',name:'Just For Today',venue:'St Pauls',addr:'120 Guyton St',region:'Whanganui'},
  {day:'Friday',time:'7:00 PM',name:'Whanganui Topic',venue:'St Pauls',addr:'120 Guyton St',region:'Whanganui'},
  // PALMERSTON NORTH
  {day:'Monday',time:'7:00 PM',name:'Literature',venue:'Quaker Hall',addr:'227 College St, West End',region:'Palmerston North'},
  {day:'Tuesday',time:'7:00 PM',name:'NA Levin',venue:'Hinamoa House',addr:'35/39 Hinemoa St, Levin',region:'Palmerston North'},
  {day:'Wednesday',time:'7:00 PM',name:'Just For Today',venue:'Quaker Hall',addr:'227 College St',region:'Palmerston North'},
  {day:'Friday',time:'7:00 PM',name:'Living Clean',venue:'Quaker Hall',addr:'227 College St',region:'Palmerston North'},
  // WELLINGTON
  {day:'Sunday',time:'4:00 PM',name:'Gift of Freedom',venue:'Salvation Army Church',addr:'4 Normanby St, Newtown',type:'Closed',region:'Wellington'},
  {day:'Monday',time:'6:30 PM',name:'Just For Today',venue:'St Mary of the Angels',addr:'17 Boulcott St',region:'Wellington'},
  {day:'Monday',time:'6:30 PM',name:'Mana Meeting',venue:'Titahi Bay Community Church',addr:'25 Mana Ave, Titahi Bay',region:'Wellington'},
  {day:'Tuesday',time:'7:00 PM',name:'Aroha Literature',venue:'Trinity Union Church',addr:'11 Hall Ave, Newtown',type:'Closed',region:'Wellington'},
  {day:'Wednesday',time:'5:30 PM',name:'Basic Text',venue:'Newtown Community Hall',addr:'71 Daniell St, Newtown',region:'Wellington'},
  {day:'Wednesday',time:'6:45 PM',name:'Wellington Women\'s',venue:'Trinity Union Church',addr:'11 Hall Ave, Newtown',type:'Women Only',region:'Wellington'},
  {day:'Wednesday',time:'7:00 PM',name:'Wellington Men\'s',venue:'Wellington High School',addr:'249 Taranaki St, Mt Cook',type:'Men Only',region:'Wellington'},
  {day:'Thursday',time:'6:00 PM',name:'Free and Queer',venue:'Trinity Union Church',addr:'11 Hall Ave, Newtown',type:'Closed',region:'Wellington'},
  {day:'Friday',time:'6:30 PM',name:'Newcomer Topic',venue:'St Mary\'s of the Angels',addr:'17 Boulcott St',region:'Wellington'},
  {day:'Saturday',time:'10:30 AM',name:'Never Too Early',venue:'St Andrews on The Terrace',addr:'30 The Terrace',region:'Wellington'},
  {day:'Saturday',time:'6:30 PM',name:'Saturday Night Simple Solutions',venue:'Trinity Union Church',addr:'11 Hall Ave, Newtown',region:'Wellington'},
  // NELSON
  {day:'Monday',time:'7:00 PM',name:'Monday Night',venue:'Nelson Baptist Church',addr:'193 Bridge St',region:'Nelson'},
  {day:'Wednesday',time:'7:00 PM',name:'Wednesday Night',venue:'Nelson Baptist Church',addr:'193 Bridge St',type:'Closed',region:'Nelson'},
  {day:'Friday',time:'6:00 PM',name:'Richmond NA',venue:'Holy Trinity Anglican',addr:'27 Dorset St, Richmond',region:'Nelson'},
  {day:'Saturday',time:'7:00 PM',name:'Steps & Traditions',venue:'Le Cren Meeting Room',addr:'276 Nayland Rd, Stoke',region:'Nelson'},
  // BLENHEIM
  {day:'Monday',time:'7:00 PM',name:'New Beginnings',venue:'Salvation Army',addr:'35 George St',region:'Blenheim'},
  {day:'Wednesday',time:'7:00 PM',name:'Keeping it Real',venue:'Salvation Army',addr:'35 George St',region:'Blenheim'},
  {day:'Thursday',time:'7:00 PM',name:'Newcomers',venue:'Riversdale Community House',addr:'131 Budge St',region:'Blenheim'},
  {day:'Saturday',time:'7:00 PM',name:'Steps and Traditions',venue:'Riversdale Community House',addr:'131 Budge St',type:'Closed',region:'Blenheim'},
  // CHRISTCHURCH
  {day:'Sunday',time:'10:30 AM',name:'Wairua',venue:'Waltham Community Cottage',addr:'201 Hastings St East, Waltham',region:'Christchurch'},
  {day:'Sunday',time:'7:00 PM',name:'Chillax',venue:'MacFarlane Park Centre',addr:'19 Acheson Ave, Mairehau',region:'Christchurch'},
  {day:'Monday',time:'11:30 AM',name:'Oasis Lunchtime',venue:'Avon Loop Cottage',addr:'28 Hurley St',region:'Christchurch'},
  {day:'Monday',time:'6:00 PM',name:'Monday\'s Message',venue:'46 Hawke Street',addr:'New Brighton',region:'Christchurch'},
  {day:'Tuesday',time:'7:00 PM',name:'Mana Wahine',venue:'Waltham Community Cottage',addr:'201 Hastings St East',type:'Women Only',region:'Christchurch'},
  {day:'Tuesday',time:'7:00 PM',name:'Southern Men\'s',venue:'Avebury House',addr:'9 Eveleyn Couzins Ave, Richmond',type:'Men Only',region:'Christchurch'},
  {day:'Tuesday',time:'7:30 PM',name:'Keeping It Real',venue:'John Knox Presbyterian',addr:'Cnr King & High St, Rangiora',type:'Closed',region:'Christchurch'},
  {day:'Wednesday',time:'11:30 AM',name:'Oasis Lunchtime',venue:'Avon Loop Cottage',addr:'28 Hurley St',region:'Christchurch'},
  {day:'Wednesday',time:'7:00 PM',name:'Phoenix',venue:'Philipstown Hub',addr:'39 Nursery Rd, Phillipstown',region:'Christchurch'},
  {day:'Thursday',time:'6:30 PM',name:'Little Town',venue:'Lyttelton Board Room',addr:'25 Canterbury St, Lyttelton',region:'Christchurch'},
  {day:'Thursday',time:'7:00 PM',name:'Hope',venue:'Avebury House',addr:'9 Eveleyn Couzins Ave',region:'Christchurch'},
  {day:'Friday',time:'11:30 AM',name:'Oasis Lunchtime',venue:'Avon Loop Cottage',addr:'28 Hurley St',region:'Christchurch'},
  {day:'Friday',time:'7:30 PM',name:'Inspiration',venue:'Abberley Cottage',addr:'15 Abberley Cres, St Albans',region:'Christchurch'},
  {day:'Saturday',time:'10:30 AM',name:'Nau Mai Haere Mai',venue:'Avon Loop Hub',addr:'29 Hurley St, Central City',region:'Christchurch'},
  {day:'Saturday',time:'6:30 PM',name:'Steps and Traditions',venue:'St Albans Community Centre',addr:'1049 Colombo St',region:'Christchurch'},
  // DUNEDIN
  {day:'Sunday',time:'11:30 AM',name:'Higher Power',venue:'Knox Church Room 5',addr:'449 George St',region:'Dunedin'},
  {day:'Sunday',time:'6:30 PM',name:'Dunedin Men\'s',venue:'St Patrick\'s Basilica',addr:'40 Macandrew Rd',type:'Men Only',region:'Dunedin'},
  {day:'Monday',time:'7:00 PM',name:'Just for Today',venue:'Knox Church Room 5',addr:'449 George St',region:'Dunedin'},
  {day:'Tuesday',time:'7:00 PM',name:'Living Clean',venue:'Broad Bay Community Centre',addr:'2 Clearwater St',region:'Dunedin'},
  {day:'Wednesday',time:'7:00 PM',name:'Newcomers',venue:'Knox Church Room 5',addr:'449 George St',type:'Closed',region:'Dunedin'},
  {day:'Thursday',time:'7:00 PM',name:'Meditation',venue:'Knox Church Room 5',addr:'449 George St',region:'Dunedin'},
  {day:'Friday',time:'7:00 PM',name:'Steps and Traditions',venue:'Knox Church Room 5',addr:'449 George St',region:'Dunedin'},
  {day:'Saturday',time:'6:00 PM',name:'Maori Meeting',venue:'Knox Church Matheson Room',addr:'449 George St',region:'Dunedin'},
  // INVERCARGILL
  {day:'Sunday',time:'7:00 PM',name:'Deep South',venue:'9 Jenkin Street',addr:'Strathern',region:'Invercargill'},
  {day:'Wednesday',time:'7:30 PM',name:'Living Clean',venue:'Holy Trinity Church',addr:'61 King St, Windsor',region:'Invercargill'},
  {day:'Thursday',time:'6:30 PM',name:'Deep South Mana Wahine',venue:'9 Jenkin Street',addr:'Strathern',type:'Women Only',region:'Invercargill'},
  // HUTT VALLEY
  {day:'Sunday',time:'4:30 PM',name:'Sunday Serenity',venue:'Petone Community House',addr:'6 Brittania St, Petone',region:'Hutt Valley'},
  {day:'Monday',time:'7:00 PM',name:'Next Right Thing',venue:'Upper Hutt Baptist',addr:'1 Milton St, Trentham',region:'Hutt Valley'},
  {day:'Tuesday',time:'7:00 PM',name:'Get Well Wainuiomata',venue:'Community Hub',addr:'1b Queen St, Wainuiomata',region:'Hutt Valley'},
  {day:'Thursday',time:'7:00 PM',name:'Attitude of Gratitude',venue:'6 Britannia Street',addr:'Petone',region:'Hutt Valley'},
  // OTAGO / SOUTHLAND
  {day:'Monday',time:'7:00 PM',name:'Oamaru NA',venue:'Orwell St Church',addr:'30 Orwell St, Oamaru',region:'Otago'},
  {day:'Wednesday',time:'6:00 PM',name:'Cromwell Meeting',venue:'Cromwell Community House',addr:'5 Murray Tce',region:'Otago'},
  {day:'Wednesday',time:'7:30 PM',name:'Just for Today',venue:'Wanaka Plunket Rooms',addr:'51 Ardmore St, Wanaka',region:'Otago'},
  {day:'Thursday',time:'7:00 PM',name:'The Pro-Gram',venue:'Salvation Army',addr:'8 Pin Oak Ave, Frankton',region:'Otago'},
  // SOUTH CANTERBURY
  {day:'Tuesday',time:'7:00 PM',name:'Timaru Tuesday',venue:'213 Church Street',addr:'Timaru',region:'South Canterbury'},
  {day:'Friday',time:'12:30 PM',name:'NA All Day',venue:'7A Craigie Avenue',addr:'Timaru',region:'South Canterbury'}
];

// ============================================================
// JAPAN MEETINGS (ENGLISH TRANSLATION - MAJOR CITIES)
// ============================================================
var japanMeetings = [
  // SAPPORO (Hokkaido)
  {day:'Sunday',time:'6:00 PM',name:'No More Crisis',venue:'Sapporo El Plaza',addr:'Kita 8-jo Nishi 3-28, Kita-ku',region:'Sapporo'},
  {day:'Monday',time:'7:00 PM',name:'Higuma',venue:'Poplar Youth Support Center',addr:'Higashi Sapporo 2-6-5-1, Shiroishi-ku',region:'Sapporo'},
  {day:'Tuesday',time:'6:30 PM',name:'Sapporo',venue:'Kita-ku Community Centre',addr:'Kita 25-jo Nishi 6-1-1',region:'Sapporo'},
  {day:'Tuesday',time:'7:00 PM',name:'Higuma',venue:'Catholic Maruyama Church',addr:'Kita 4-jo Nishi 23-2-10, Chuo-ku',region:'Sapporo'},
  {day:'Tuesday',time:'7:00 PM',name:'No Name (LGBT)',venue:'Sapporo El Plaza',addr:'Kita 8-jo Nishi 3-28',type:'LGBT Only',region:'Sapporo'},
  {day:'Wednesday',time:'6:30 PM',name:'Bonten',venue:'Catholic Sapporo Diocese',addr:'Kita 1-jo Higashi 6-10, Chuo-ku',region:'Sapporo'},
  {day:'Wednesday',time:'7:00 PM',name:'Rising Sun',venue:'Catholic Maruyama Church',addr:'Kita 4-jo Nishi 23-2-10',region:'Sapporo'},
  {day:'Thursday',time:'6:30 PM',name:'As One',venue:'Kita-ku Community Centre',addr:'Kita 25-jo Nishi 6-1-1',region:'Sapporo'},
  {day:'Friday',time:'6:30 PM',name:'Introduction',venue:'Toyohira Church',addr:'Toyohira 6-jo 3-5-15, Toyohira-ku',region:'Sapporo'},
  {day:'Saturday',time:'1:30 PM',name:'No Name',venue:'Catholic Sapporo Bishop\'s Office',addr:'Kita 1-jo Higashi 6-10',region:'Sapporo'},
  {day:'Saturday',time:'6:30 PM',name:'Introduction',venue:'Kita-ku Community Centre',addr:'Kita 25-jo Nishi 6-1-1',region:'Sapporo'},
  // SENDAI (Tohoku)
  {day:'Sunday',time:'7:00 PM',name:'Sendai',venue:'Sendai Silver Centre',addr:'Hanakyo-in 1-3-2, Aoba-ku',region:'Sendai'},
  {day:'Monday',time:'7:00 PM',name:'Sendai',venue:'Ipponsugi Catholic Church',addr:'Ipponsugi-cho 1-2, Wakabayashi-ku',region:'Sendai'},
  {day:'Tuesday',time:'7:00 PM',name:'Sendai',venue:'El Park Sendai 5F',addr:'Ichiban-cho 4-11-1, Aoba-ku',region:'Sendai'},
  {day:'Wednesday',time:'6:15 PM',name:'Spiritual Growth',venue:'Taihaku Central Community Centre',addr:'Nagamachi 5-3-2, Taihaku-ku',region:'Sendai'},
  {day:'Thursday',time:'7:00 PM',name:'Sendai',venue:'Kashiwagi Community Centre',addr:'Kashiwagi 3-3-1, Aoba-ku',region:'Sendai'},
  {day:'Friday',time:'7:00 PM',name:'Sendai',venue:'Tohoku-kai Hospital',addr:'Kashiwagi 1-8-7, Aoba-ku',region:'Sendai'},
  {day:'Saturday',time:'7:00 PM',name:'Sendai',venue:'Mototera-koji Catholic Church',addr:'Honcho 1-2-12, Aoba-ku',region:'Sendai'},
  // TOKYO
  {day:'Sunday',time:'1:00 PM',name:'Brain Damage Reborn',venue:'Arakawa Learning Centre',addr:'Arakawa 3-49-1, Arakawa-ku',region:'Tokyo'},
  {day:'Sunday',time:'7:00 PM',name:'New Life',venue:'Koiwa Catholic Church',addr:'Nishi-Koiwa 4-4-1, Edogawa-ku',region:'Tokyo'},
  {day:'Sunday',time:'7:00 PM',name:'Shinjuku',venue:'Fukagawa Church',addr:'Kiba 6-5-19, Koto-ku',region:'Tokyo'},
  {day:'Sunday',time:'7:00 PM',name:'Hachioji JFT',venue:'Lifelong Learning Centre',addr:'Higashi-cho 5-6, Hachioji',region:'Tokyo'},
  {day:'Monday',time:'7:00 PM',name:'Nakano At Home',venue:'Smile Nakano',addr:'Nakano 5-68-7, Nakano-ku',region:'Tokyo'},
  {day:'Monday',time:'7:00 PM',name:'Welcome Growing Up',venue:'Shin-ai Church',addr:'Higashi-Nippori 5-18-8, Arakawa-ku',type:'Women Only',region:'Tokyo'},
  {day:'Monday',time:'7:00 PM',name:'Daiba',venue:'Daiba Community Centre',addr:'Daiba 1-5-1, Minato-ku',region:'Tokyo'},
  {day:'Tuesday',time:'6:15 PM',name:'English Meeting',venue:'Franciscan Chapel 2F-204',addr:'Roppongi 4-2-37, Minato-ku',type:'English (Closed)',region:'Tokyo'},
  {day:'Tuesday',time:'7:00 PM',name:'Last Fort',venue:'Umeda Catholic Church',addr:'Umeda 7-19-22, Adachi-ku',region:'Tokyo'},
  {day:'Tuesday',time:'7:00 PM',name:'Shinjuku (LGBT)',venue:'Nakano Momozono Church',addr:'Nakano 5-3-14',type:'LGBT (Closed)',region:'Tokyo'},
  {day:'Tuesday',time:'7:00 PM',name:'Karasuyama Get Back',venue:'Karasuyama Community Centre',addr:'Minami-Karasuyama 6-2-19, Setagaya-ku',region:'Tokyo'},
  {day:'Tuesday',time:'7:00 PM',name:'Shinjuku Gentle',venue:'AIC Building B1F',addr:'Yocho-machi 14-4, Shinjuku-ku',region:'Tokyo'},
  {day:'Wednesday',time:'7:00 PM',name:'Okubo',venue:'Kashiwagi Church',addr:'Kita-Shinjuku 3-1-18',region:'Tokyo'},
  {day:'Wednesday',time:'7:00 PM',name:'With Fellowship',venue:'Bunkyo Community Centre',addr:'Hongo 4-15-14, Bunkyo-ku',region:'Tokyo'},
  {day:'Wednesday',time:'6:30 PM',name:'50 Percent',venue:'Matsuhara Catholic Church',addr:'Matsuhara 2-28-5, Setagaya-ku',region:'Tokyo'},
  {day:'Thursday',time:'7:00 PM',name:'Welcome Growing Up',venue:'St Alban\'s Church',addr:'Shiba-koen 3-6-25, Minato-ku',region:'Tokyo'},
  {day:'Thursday',time:'7:00 PM',name:'It Ain\'t Therapy (English)',venue:'Tokyo Union Church B1',addr:'Jingumae 5-7-7, Shibuya-ku',type:'English',region:'Tokyo'},
  {day:'Thursday',time:'7:00 PM',name:'Karasuyama Get Back',venue:'Karasuyama Community Centre',addr:'Minami-Karasuyama 6-2-19',region:'Tokyo'},
  {day:'Thursday',time:'7:00 PM',name:'Tokyo',venue:'Toshima Catholic Church',addr:'Nagasaki 1-28-22, Toshima-ku',region:'Tokyo'},
  {day:'Thursday',time:'7:00 PM',name:'Step Up Nerima',venue:'Asahi-cho Community Hall',addr:'Takamatsu 5-23-15, Nerima-ku',region:'Tokyo'},
  {day:'Friday',time:'6:00 PM',name:'Meguro Petit',venue:'Meguro Catholic Church',addr:'Kami-Osaki 4-6-22, Shinagawa-ku',region:'Tokyo'},
  {day:'Friday',time:'7:00 PM',name:'Workers',venue:'Ueno Catholic Church',addr:'Shitaya 1-5-9, Taito-ku',region:'Tokyo'},
  {day:'Friday',time:'7:00 PM',name:'Good Night',venue:'Tokyo Central Church',addr:'Kita-Shinjuku 1-24-12',region:'Tokyo'},
  {day:'Saturday',time:'7:00 PM',name:'Asakusa',venue:'Asakusa Church',addr:'Nishi-Asakusa 3-4-5, Taito-ku',region:'Tokyo'},
  {day:'Saturday',time:'7:00 PM',name:'White',venue:'Takada Community Room',addr:'Takada 3-18-3, Toshima-ku',region:'Tokyo'},
  {day:'Saturday',time:'7:00 PM',name:'K.I.S.S.',venue:'St Ignatius Church',addr:'Kojimachi 6-5, Chiyoda-ku',region:'Tokyo'},
  // YOKOHAMA / KANAGAWA
  {day:'Sunday',time:'7:00 PM',name:'Kawasaki Riverside',venue:'Plaza Daishi Hall',addr:'Daishi Ekimae 1-1-5, Kawasaki-ku',region:'Yokohama'},
  {day:'Monday',time:'1:30 PM',name:'Yokohama NA',venue:'Naka-ku Welfare Centre',addr:'Yamashita-cho 2, Naka-ku',region:'Yokohama'},
  {day:'Monday',time:'7:00 PM',name:'Yokohama Outsider',venue:'Minami-ku Welfare Centre',addr:'Urafune-cho 3-46, Minami-ku',region:'Yokohama'},
  {day:'Tuesday',time:'6:30 PM',name:'Sanctuary',venue:'Naka-ku Welfare Centre',addr:'Yamashita-cho 2, Naka-ku',region:'Yokohama'},
  {day:'Wednesday',time:'7:00 PM',name:'Yokohama NA',venue:'Naka-ku Welfare Centre',addr:'Yamashita-cho 2, Naka-ku',region:'Yokohama'},
  {day:'Thursday',time:'7:00 PM',name:'Yokohama Outsider',venue:'Catholic Sueyoshi Church',addr:'Sueyoshi-cho 1-13, Naka-ku',region:'Yokohama'},
  {day:'Thursday',time:'7:00 PM',name:'Green Room',venue:'Catholic Nakahara Church',addr:'Imai Minami-cho 500, Nakahara-ku',region:'Yokohama'},
  {day:'Friday',time:'7:00 PM',name:'Never Alone',venue:'Kikuna Community Centre',addr:'Kikuna 6-18-10, Kohoku-ku',region:'Yokohama'},
  {day:'Friday',time:'7:00 PM',name:'Kawasaki Riverside',venue:'Mizonokuchi Catholic Church',addr:'Futago 5-15-7, Takatsu-ku',region:'Yokohama'},
  {day:'Saturday',time:'7:00 PM',name:'Odawara',venue:'Catholic Odawara Church',addr:'Sakae-cho 4-6-5, Odawara',region:'Yokohama'},
  // SHIZUOKA
  {day:'Tuesday',time:'7:00 PM',name:'Shizuoka One Day',venue:'Catholic Shizuoka Church',addr:'Jonai-cho 1-5, Aoi-ku',region:'Shizuoka'},
  {day:'Wednesday',time:'7:00 PM',name:'Shizuoka One Day',venue:'Shimizu Info Plaza',addr:'Aioi-cho 6-17, Shimizu-ku',region:'Shizuoka'},
  {day:'Friday',time:'7:00 PM',name:'Hamamatsu Recovery',venue:'Welfare Exchange Centre',addr:'Naruko-cho 140-8, Naka-ku',region:'Shizuoka'}
];
-e 
// --- BMLT DATA ---
var BMLT_SERVERS = {
  'ie': 'https://bmlt.nasouth.ie/main_server',
  'de': 'https://www.narcotics-anonymous.de/bmlt',
  'at': 'https://www.narcotics-anonymous.de/bmlt',
  'br': 'https://bmlt.na.org.br/ativo/main_server',
  'ca': 'https://canaacna.org/meetings/main_server',
  'au': 'https://bmlt.na.org.au/main_server',
  'nz': 'https://bmlt.na.org.au/main_server',
  'fr': 'https://bmlt.narcotiquesanonymes.org',
  'us': 'auto'
};

// Countries with their own meeting finders (not BMLT) — used as smart fallback
var COUNTRY_FINDERS = {
  'gb': { name: 'United Kingdom', url: 'https://meetings.ukna.org/meeting/search', label: 'UKNA Meeting Finder', postcode_param: 'field_meeting_location_value' },
  'jp': { name: 'Japan',          url: 'https://najapan.org', label: 'NA Japan Meeting Search', postcode_param: null },
  'ir': { name: 'Iran',           url: 'https://www.na-iran.org/meetings', label: 'NA Iran Meeting Search', postcode_param: null },
  'nz': { name: 'New Zealand',    url: 'https://nzna.org/meetings/', label: 'NA New Zealand', postcode_param: null },
  'za': { name: 'South Africa',   url: 'https://www.na.org.za/meetings', label: 'NA South Africa', postcode_param: null },
  'in': { name: 'India',          url: 'https://www.naindia.org/meeting-schedule', label: 'NA India Meeting Schedule', postcode_param: null },
  'il': { name: 'Israel',         url: 'https://na-israel.org/meetings', label: 'NA Israel Meetings', postcode_param: null },
  'sg': { name: 'Singapore',      url: 'https://www.nasingapore.org/meetings', label: 'NA Singapore', postcode_param: null },
  'th': { name: 'Thailand',       url: 'https://na-thailand.org/meetings', label: 'NA Thailand', postcode_param: null }
};

var BMLT_US_SERVERS = [
  { url:'https://bmlt.wszf.org/main_server',    minLng:-180, maxLng:-104, minLat:24,  maxLat:72  },
  { url:'https://bmlt.sezf.org/main_server',    minLng:-104, maxLng:-75,  minLat:24,  maxLat:38  },
  { url:'https://pszfna.org/main_server',       minLng:-104, maxLng:-88,  minLat:35,  maxLat:49  },
  { url:'https://bmlt.newyorkna.org/main_server',minLng:-88, maxLng:-66,  minLat:38,  maxLat:49  },
  { url:'https://nerna.org/main_server',        minLng:-76,  maxLng:-66,  minLat:41,  maxLat:48  }
];

var BMLT_DAYS = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
