workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.cleanliving
      vars:
        BUNDLE_ID: "app.cleanliving"
        XCODE_WORKSPACE: "ios/src/Clean Living.xcworkspace"
        XCODE_SCHEME: "Clean Living"
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios/src
          pod install
      - name: Build iOS
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
