opt_out_usage
default_platform(:ios)
platform :ios do
  desc "Upload to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"]
    )
    
    match(
      type: "appstore",
      app_identifier: "app.cleanliving",
      git_url: "https://github.com/clarehobson/certificates.git",
      api_key: api_key,
      readonly: false
    )
    
    build_app(
      workspace: "ios/src/Clean Living.xcworkspace",
      scheme: "Clean Living",
      configuration: "Release",
      team_id: "D3NH4Q92W8"
    )
    
    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )
  end
end
